// ui-strings.ts — translations of the hard-coded interface text.
//
// Keyed by the EXACT English literal passed to t() (lib/i18n.tsx), each row is
// [Korean, Simplified Chinese, Japanese]. A missing row (or empty cell) shows the
// English. `{name}` placeholders are filled in after the lookup, so keep them
// intact in every language. Acronyms, tickers and company names stay as they are.

type Row = [ko: string, zh: string, ja: string];

export const UI: Record<string, Row> = {
  // ── Language switch / app shell (page.tsx) ──────────────────────────────
  "Language": ["언어", "语言", "言語"],
  "Skip to research": ["리서치로 건너뛰기", "跳到研究内容", "リサーチへスキップ"],
  "Open filters": ["필터 열기", "打开筛选", "フィルターを開く"],
  "Filters": ["필터", "筛选", "フィルター"],
  "AI Supply Chain": ["AI 공급망", "AI 供应链", "AIサプライチェーン"],
  "Research the companies behind AI.": ["AI를 움직이는 기업을 리서치하세요.", "研究 AI 背后的公司。", "AIを支える企業をリサーチ。"],
  "Transcript-grounded research": ["실적 발표 원문 기반 리서치", "基于电话会议原文的研究", "決算説明会の原文に基づくリサーチ"],
  "Research views": ["리서치 보기", "研究视图", "リサーチビュー"],
  "3D Tower": ["3D 타워", "3D 塔", "3D タワー"],
  "Open the 3D Supply-chain Tower in a new window": ["새 창에서 3D 공급망 타워 열기", "在新窗口中打开 3D 供应链塔", "新しいウィンドウで3Dサプライチェーンタワーを開く"],
  "RESEARCH WORKSPACE": ["리서치 워크스페이스", "研究工作区", "リサーチワークスペース"],
  // tabs
  "Graph": ["그래프", "图谱", "グラフ"],
  "Chain 2D": ["체인 2D", "产业链 2D", "チェーン2D"],
  "Generations": ["세대 전환", "代际", "世代"],
  "Exposure": ["익스포저", "敞口", "エクスポージャー"],
  "Timelines": ["타임라인", "时间线", "タイムライン"],
  "Screener": ["스크리너", "筛选器", "スクリーナー"],
  "Picks": ["픽", "精选", "ピック"],
  "Capex": ["설비투자", "资本开支", "設備投資"],
  "Status": ["현황", "状态", "ステータス"],
  "Ask": ["질문", "提问", "質問"],
  "Semi Bot": ["Semi Bot", "Semi Bot", "Semi Bot"],
  // tab groups (2026-10-01). Keyed "Tab group: X" because "Signals" already has
  // a different translation elsewhere (시그널); page.tsx shows the bare English name.
  "Tab group: Map": ["지도", "地图", "マップ"],
  "Tab group: Companies": ["기업", "公司", "企業"],
  "Tab group: Signals": ["신호", "信号", "シグナル"],
  "Tab group: Tools": ["도구", "工具", "ツール"],
  "Research groups": ["리서치 그룹", "研究分组", "リサーチグループ"],
  // view intros
  "Follow the connections.": ["연결을 따라가 보세요.", "顺着关联关系探索。", "つながりをたどる。"],
  "Explore companies and the supply relationships that connect them.": ["기업들과 그들을 잇는 공급 관계를 탐색하세요.", "探索各家公司以及连接它们的供应关系。", "企業と、それらを結ぶ供給関係を探索します。"],
  "One product. Every layer.": ["하나의 제품, 모든 레이어.", "一个产品，贯穿每一层。", "ひとつの製品、すべてのレイヤー。"],
  "Trace a product chain from materials and equipment to its end customers.": ["소재·장비에서 최종 고객까지 제품 체인을 추적하세요.", "从材料和设备一路追踪到终端客户的产品链。", "素材・装置から最終顧客まで製品チェーンを追跡します。"],
  "See what changes next.": ["다음에 무엇이 바뀌는지 보세요.", "看清下一步的变化。", "次に何が変わるかを見る。"],
  "Compare product generations and the suppliers gained, retained, or lost.": ["제품 세대를 비교하고 신규·유지·이탈 공급사를 확인하세요.", "对比产品世代，以及新增、保留或流失的供应商。", "製品世代を比較し、獲得・維持・喪失したサプライヤーを確認します。"],
  "Find the companies behind a chain.": ["체인 뒤에 있는 기업을 찾아보세요.", "找出产业链背后的公司。", "チェーンを支える企業を見つける。"],
  "Explore sourced exposure, customer concentration, and generation changes.": ["출처가 있는 익스포저, 고객 집중도, 세대 변화를 살펴보세요.", "查看有出处的敞口、客户集中度和世代变化。", "出典付きのエクスポージャー、顧客集中度、世代の変化を探索します。"],
  "Put the signals in sequence.": ["시그널을 시간 순으로 정리하세요.", "按时间顺序梳理信号。", "シグナルを時系列で並べる。"],
  "Track roadmaps, capacity, and product milestones across the supply chain.": ["공급망 전반의 로드맵, 생산능력, 제품 마일스톤을 추적하세요.", "追踪整个供应链的路线图、产能和产品里程碑。", "サプライチェーン全体のロードマップ、生産能力、製品マイルストーンを追跡します。"],
  "Compare the companies.": ["기업을 비교하세요.", "对比各家公司。", "企業を比較する。"],
  "Review the latest reported results, guidance, supply status, and catalysts.": ["최신 실적, 가이던스, 공급 상황, 촉매를 확인하세요.", "查看最新业绩、指引、供应状况和催化因素。", "最新の業績、ガイダンス、供給状況、カタリストを確認します。"],
  "Track the picks.": ["픽을 추적하세요.", "追踪精选组合。", "ピックを追跡する。"],
  "Two ranked one-quarter baskets, priced live against their 2026-09-18 entry.": ["2026-09-18 진입가 대비 실시간으로 평가되는 한 분기짜리 순위 바스켓 두 개.", "两个为期一个季度的排名组合，以 2026-09-18 建仓价实时计价。", "2026-09-18のエントリー価格に対してリアルタイムで評価される、1四半期のランキング・バスケット2つ。"],
  "Follow the investment.": ["투자 흐름을 따라가세요.", "追踪投资流向。", "投資の流れを追う。"],
  "Compare capital spending and contracted demand across cloud infrastructure.": ["클라우드 인프라 전반의 설비투자와 계약된 수요를 비교하세요.", "对比云基础设施的资本开支与已签约需求。", "クラウドインフラ全体の設備投資と契約済み需要を比較します。"],
  "Know what to enrich next.": ["다음에 무엇을 보강할지 파악하세요.", "了解下一步该补充什么。", "次に何を拡充すべきかを把握する。"],
  "See what is waiting, what is overdue, and which enrich command to run next.": ["대기 중인 것, 기한이 지난 것, 다음에 실행할 enrich 명령을 확인하세요.", "查看待处理、已逾期的内容，以及下一步要运行的 enrich 命令。", "待機中・期限超過の項目と、次に実行する enrich コマンドを確認します。"],
  "Start with a question.": ["질문으로 시작하세요.", "从一个问题开始。", "質問から始める。"],
  "Explore the stored signals and contracts with source-linked answers.": ["저장된 시그널과 계약을 출처가 연결된 답변으로 탐색하세요.", "通过附带出处链接的回答，探索已存储的信号和合同。", "保存されたシグナルと契約を、出典リンク付きの回答で探索します。"],
  "Your Semi Bot workspace.": ["Semi Bot 워크스페이스.", "你的 Semi Bot 工作区。", "Semi Bot ワークスペース。"],
  "Open the trading dashboard alongside your supply-chain research.": ["공급망 리서치와 함께 트레이딩 대시보드를 여세요.", "在供应链研究旁打开交易仪表盘。", "サプライチェーン・リサーチと並べてトレーディング・ダッシュボードを開きます。"],
  // workspace states + graph tools
  "Interactive 3D map": ["인터랙티브 3D 지도", "交互式 3D 地图", "インタラクティブ3Dマップ"],
  "We couldn't load your research.": ["리서치 데이터를 불러오지 못했습니다.", "无法加载研究数据。", "リサーチデータを読み込めませんでした。"],
  "Check your connection and try again. Your filter selections will stay in place.": ["연결을 확인하고 다시 시도하세요. 필터 선택은 그대로 유지됩니다.", "请检查网络连接后重试。筛选条件会保留。", "接続を確認して再試行してください。フィルターの選択はそのまま残ります。"],
  "Try again": ["다시 시도", "重试", "再試行"],
  "Loading your research workspace": ["리서치 워크스페이스를 불러오는 중", "正在加载研究工作区", "リサーチワークスペースを読み込み中"],
  "Connecting companies, product chains, and source documents…": ["기업, 제품 체인, 원문 자료를 연결하는 중…", "正在连接公司、产品链和原始文件…", "企業、製品チェーン、原資料を接続中…"],
  "Find a company": ["기업 찾기", "查找公司", "企業を検索"],
  "to search": ["검색", "搜索", "で検索"],
  "Visible graph summary": ["표시 중인 그래프 요약", "当前图谱概要", "表示中のグラフの概要"],
  "Companies": ["기업", "公司", "企業"],
  "Connections": ["연결", "关联", "つながり"],
  "Active chains": ["활성 체인", "启用的产业链", "有効なチェーン"],
  "Click a company for details. Drag to rotate · Scroll to zoom.": ["기업을 클릭하면 상세 정보가 열립니다. 드래그로 회전 · 스크롤로 확대/축소.", "点击公司查看详情。拖动旋转 · 滚动缩放。", "企業をクリックすると詳細を表示。ドラッグで回転・スクロールでズーム。"],
  "Stop showing only {label} makers": ["{label} 제조사만 보기 해제", "取消仅显示 {label} 厂商", "{label} メーカーのみの表示を解除"],
  "Showing “{label}” · {n} companies": ["“{label}” 표시 중 · {n}개 기업", "正在显示“{label}” · {n} 家公司", "“{label}” を表示中 · {n}社"],
  "Reset graph filters": ["그래프 필터 초기화", "重置图谱筛选", "グラフのフィルターをリセット"],
  "All filters selected": ["모든 필터 선택됨", "已选择全部筛选", "すべてのフィルターを選択中"],
  "No companies in this view": ["이 보기에 해당하는 기업이 없습니다", "当前视图中没有公司", "この表示に該当する企業はありません"],
  "Choose another chain, layer, or domain, or restore all graph filters.": ["다른 체인·레이어·도메인을 선택하거나 그래프 필터를 모두 복원하세요.", "请选择其他产业链、层级或领域，或恢复全部图谱筛选。", "別のチェーン・レイヤー・ドメインを選ぶか、グラフのフィルターをすべて戻してください。"],
  "Show all companies": ["모든 기업 보기", "显示所有公司", "すべての企業を表示"],
  "Semi Bot dashboard, shown inline.": ["Semi Bot 대시보드 (페이지 내 표시).", "Semi Bot 仪表盘（内嵌显示）。", "Semi Bot ダッシュボード（ページ内表示）。"],
  "Open in a new tab": ["새 탭에서 열기", "在新标签页中打开", "新しいタブで開く"],
  "Semi Bot dashboard": ["Semi Bot 대시보드", "Semi Bot 仪表盘", "Semi Bot ダッシュボード"],

  // ── Layers & domains (lib/taxonomy.ts) ─────────────────────────────────
  "Application": ["애플리케이션", "应用", "アプリケーション"],
  "AI Models": ["AI 모델", "AI 模型", "AIモデル"],
  "Software Infrastructure": ["소프트웨어 인프라", "软件基础设施", "ソフトウェアインフラ"],
  "Cloud Infrastructure": ["클라우드 인프라", "云基础设施", "クラウドインフラ"],
  "System Integration": ["시스템 통합", "系统集成", "システムインテグレーション"],
  "Compute Hardware": ["컴퓨팅 하드웨어", "计算硬件", "コンピュートハードウェア"],
  "Memory": ["메모리", "存储器", "メモリ"],
  "Interconnect": ["인터커넥트", "互连", "インターコネクト"],
  "Advanced Packaging": ["첨단 패키징", "先进封装", "先端パッケージング"],
  "Semiconductor Foundry": ["반도체 파운드리", "半导体代工", "半導体ファウンドリ"],
  "Semiconductor Equipment": ["반도체 장비", "半导体设备", "半導体製造装置"],
  "Semiconductor Materials": ["반도체 소재", "半导体材料", "半導体材料"],
  "Critical Minerals": ["핵심 광물", "关键矿产", "重要鉱物"],
  "Power Infrastructure": ["전력 인프라", "电力基础设施", "電力インフラ"],
  "Thermal Management": ["열 관리", "热管理", "熱管理"],
  "Security": ["보안", "安全", "セキュリティ"],
  "Edge & Physical AI": ["엣지·피지컬 AI", "边缘与物理 AI", "エッジ・フィジカルAI"],
  "Other": ["기타", "其他", "その他"],

  // ── Chain & topic names (lib/taxonomy.ts SLUG_NAMES) ─────────────────────
  "NVIDIA Vera Rubin": ["NVIDIA 베라 루빈", "英伟达 Vera Rubin", "NVIDIA Vera Rubin"],
  "Google TPU v7 (Ironwood)": ["구글 TPU v7 (Ironwood)", "谷歌 TPU v7 (Ironwood)", "Google TPU v7 (Ironwood)"],
  "NVIDIA B200 (Blackwell)": ["NVIDIA B200 (블랙웰)", "英伟达 B200 (Blackwell)", "NVIDIA B200 (Blackwell)"],
  "Optical Networking": ["광 네트워킹", "光网络", "光ネットワーク"],
  "Broadcom Custom ASIC": ["브로드컴 커스텀 ASIC", "博通定制 ASIC", "Broadcom カスタムASIC"],
  "HBM Memory": ["HBM 메모리", "HBM 存储器", "HBMメモリ"],
  "NAND Flash": ["낸드 플래시", "NAND 闪存", "NANDフラッシュ"],
  "Data Center CPU": ["데이터센터 CPU", "数据中心 CPU", "データセンターCPU"],
  "MLCC": ["MLCC", "MLCC", "MLCC"],
  "Power & Cooling": ["전력·냉각", "电力与散热", "電力・冷却"],
  "Foundry": ["파운드리", "晶圆代工", "ファウンドリ"],
  "AMD MI450 / Helios": ["AMD MI450 / Helios", "AMD MI450 / Helios", "AMD MI450 / Helios"],
  "AWS Trainium2": ["AWS 트레이니엄2", "AWS Trainium2", "AWS Trainium2"],
  "Packaging & Substrate": ["패키징·기판", "封装与基板", "パッケージング・基板"],
  "Google TPU v8t": ["구글 TPU v8t", "谷歌 TPU v8t", "Google TPU v8t"],
  "Google TPU v8i": ["구글 TPU v8i", "谷歌 TPU v8i", "Google TPU v8i"],
  "AMD MI355": ["AMD MI355", "AMD MI355", "AMD MI355"],
  "AWS Trainium3": ["AWS 트레이니엄3", "AWS Trainium3", "AWS Trainium3"],
  "Neocloud": ["네오클라우드", "新兴云（Neocloud）", "ネオクラウド"],
  "Power Semiconductors": ["전력 반도체", "功率半导体", "パワー半導体"],
  "AI Bio": ["AI 바이오", "AI 生物", "AIバイオ"],
  "Supply tightness": ["공급 부족", "供应紧张", "供給逼迫"],
  "Generation transitions": ["세대 전환", "代际转换", "世代移行"],
  "Product launches": ["제품 출시", "产品发布", "製品投入"],
  "HBM": ["HBM", "HBM", "HBM"],
  "NAND & storage": ["낸드·스토리지", "NAND 与存储", "NAND・ストレージ"],
  "Optical speed": ["광 전송 속도", "光模块速率", "光伝送速度"],
  "Silicon photonics": ["실리콘 포토닉스", "硅光子", "シリコンフォトニクス"],
  "CPO": ["CPO", "CPO", "CPO"],
  "CPU": ["CPU", "CPU", "CPU"],
  "OCS": ["OCS", "OCS", "OCS"],
  // ── Sidebar ──────────────────────────────────────────────────────────────
  "Select all chains": ["체인 모두 선택", "全选产业链", "チェーンをすべて選択"],
  "Clear all chains": ["체인 모두 해제", "清除全部产业链", "チェーンをすべて解除"],
  "Select all layers": ["레이어 모두 선택", "全选层级", "レイヤーをすべて選択"],
  "Clear all layers": ["레이어 모두 해제", "清除全部层级", "レイヤーをすべて解除"],
  "Select all domains": ["도메인 모두 선택", "全选领域", "ドメインをすべて選択"],
  "Clear all domains": ["도메인 모두 해제", "清除全部领域", "ドメインをすべて解除"],
  "All": ["전체", "全部", "すべて"],
  "None": ["없음", "无", "なし"],
  "{n} visible companies": ["표시 중인 기업 {n}개", "当前显示 {n} 家公司", "表示中の企業 {n}社"],
  "Legend": ["범례", "图例", "凡例"],
  "node colors": ["노드 색상", "节点颜色", "ノードの色"],
  "Layers (top → bottom)": ["레이어 (위 → 아래)", "层级（自上而下）", "レイヤー（上 → 下）"],
  "Domains": ["도메인", "领域", "ドメイン"],
  "Graph filters": ["그래프 필터", "图谱筛选", "グラフのフィルター"],
  "Close filters": ["필터 닫기", "关闭筛选", "フィルターを閉じる"],
  "EXPLORE THE NETWORK": ["네트워크 탐색", "探索网络", "ネットワークを探索"],
  "Narrow the Graph by product chain, layer, or domain. Other views have their own filters.": ["제품 체인, 레이어, 도메인으로 그래프를 좁혀 보세요. 다른 보기에는 각자의 필터가 있습니다.", "按产品链、层级或领域缩小图谱范围。其他视图有各自的筛选。", "製品チェーン、レイヤー、ドメインでグラフを絞り込みます。他のビューには専用のフィルターがあります。"],
  "Filter chains, layers…": ["체인, 레이어 필터…", "筛选产业链、层级…", "チェーン、レイヤーを絞り込み…"],
  "Find a chain, layer, or domain filter": ["체인·레이어·도메인 필터 찾기", "查找产业链、层级或领域筛选", "チェーン・レイヤー・ドメインのフィルターを探す"],
  "Turn every chain, layer and domain back on": ["모든 체인, 레이어, 도메인을 다시 켭니다", "重新启用所有产业链、层级和领域", "すべてのチェーン、レイヤー、ドメインを再びオンにする"],
  "Reset filters": ["필터 초기화", "重置筛选", "フィルターをリセット"],
  "{n} filter off": ["필터 {n}개 꺼짐", "{n} 个筛选已关闭", "{n}個のフィルターがオフ"],
  "{n} filters off": ["필터 {n}개 꺼짐", "{n} 个筛选已关闭", "{n}個のフィルターがオフ"],
  "dot = each item's color in the graph": ["점 = 그래프에서 각 항목의 색상", "圆点 = 该项在图谱中的颜色", "点 = グラフ上での各項目の色"],
  "number = visible companies": ["숫자 = 표시 중인 기업 수", "数字 = 当前显示的公司数", "数字 = 表示中の企業数"],
  "Chains": ["체인", "产业链", "チェーン"],
  "this chain's edge color in the graph": ["그래프에서 이 체인의 연결선 색상", "该产业链在图谱中的连线颜色", "グラフ上でのこのチェーンのエッジの色"],
  "no match": ["일치 항목 없음", "无匹配", "該当なし"],
  "Layers": ["레이어", "层级", "レイヤー"],
  "layer node color in the graph": ["그래프에서 레이어 노드 색상", "该层级在图谱中的节点颜色", "グラフ上でのレイヤーのノードの色"],
  "domain node color in the graph": ["그래프에서 도메인 노드 색상", "该领域在图谱中的节点颜色", "グラフ上でのドメインのノードの色"],
  "Fade companies with no data in the last 180 days": ["최근 180일간 데이터가 없는 기업을 흐리게 표시", "淡化最近 180 天没有数据的公司", "過去180日間データのない企業を薄く表示"],
  "Dim stale nodes (180d)": ["오래된 노드 흐리게 (180일)", "淡化过时节点（180 天）", "古いノードを薄く表示（180日）"],
  "Appearance": ["화면 설정", "外观", "表示設定"],
  "Frosted-glass panel material": ["반투명 유리 패널 효과", "磨砂玻璃面板效果", "すりガラス風パネル"],
  "Liquid Glass": ["리퀴드 글래스", "液态玻璃", "リキッドグラス"],
  // ── SearchBox ────────────────────────────────────────────────────────────
  "Search company, ticker, or product": ["기업, 티커, 제품 검색", "搜索公司、代码或产品", "企業、ティッカー、製品を検索"],
  "Search company, ticker, product…": ["기업, 티커, 제품 검색…", "搜索公司、代码、产品…", "企業、ティッカー、製品を検索…"],
  "Clear search": ["검색 지우기", "清除搜索", "検索をクリア"],
  "Recent": ["최근", "最近", "最近"],
  "No company matches “{q}”": ["“{q}”와 일치하는 기업이 없습니다", "没有与“{q}”匹配的公司", "“{q}” に一致する企業はありません"],
  "{n} companies · show on graph": ["{n}개 기업 · 그래프에 표시", "{n} 家公司 · 在图谱中显示", "{n}社 · グラフに表示"],
  "↑ ↓ to move · Enter to open · Esc to close": ["↑ ↓ 이동 · Enter 열기 · Esc 닫기", "↑ ↓ 移动 · Enter 打开 · Esc 关闭", "↑ ↓ 移動 · Enter で開く · Esc で閉じる"],
  "{n} chain": ["체인 {n}개", "{n} 条产业链", "{n}チェーン"],
  "{n} chains": ["체인 {n}개", "{n} 条产业链", "{n}チェーン"],
  // ── Graph3D ──────────────────────────────────────────────────────────────
  "last data {date}": ["최근 데이터 {date}", "最新数据 {date}", "最新データ {date}"],
  "no dated signals": ["날짜가 있는 시그널 없음", "无带日期的信号", "日付付きシグナルなし"],
  "outside the current focus": ["현재 포커스 범위 밖", "不在当前焦点范围内", "現在のフォーカス範囲外"],
  "Failed to load 3D graph library:": ["3D 그래프 라이브러리를 불러오지 못했습니다:", "3D 图谱库加载失败：", "3Dグラフライブラリを読み込めませんでした："],
  "Initializing 3D engine…": ["3D 엔진 초기화 중…", "正在初始化 3D 引擎…", "3Dエンジンを初期化中…"],
  "Graph controls": ["그래프 컨트롤", "图谱控件", "グラフ操作"],
  "Frame every visible company (or the focused neighborhood)": ["표시 중인 모든 기업(또는 포커스된 주변)을 화면에 맞춥니다", "将所有可见公司（或焦点邻域）纳入视野", "表示中のすべての企業（またはフォーカス中の近傍）を画面に収める"],
  "Fit view": ["화면 맞춤", "适配视图", "全体表示"],
  "Leave focus mode and frame the whole graph": ["포커스 모드를 끝내고 전체 그래프를 보여줍니다", "退出焦点模式并显示整个图谱", "フォーカスモードを終了してグラフ全体を表示"],
  "Reset": ["초기화", "重置", "リセット"],
  "Neighborhood depth": ["주변 범위", "邻域深度", "近傍の深さ"],
  "Direct suppliers and customers only": ["직접 공급사와 고객만", "仅直接供应商和客户", "直接のサプライヤーと顧客のみ"],
  "1 hop": ["1단계", "1 跳", "1ホップ"],
  "Also the suppliers' suppliers and the customers' customers": ["공급사의 공급사, 고객의 고객까지", "也包括供应商的供应商和客户的客户", "サプライヤーのサプライヤー、顧客の顧客まで含める"],
  "2 hops": ["2단계", "2 跳", "2ホップ"],
  "{n} companies within {h} hop(s) of {name}": ["{name}에서 {h}단계 이내 기업 {n}개", "距 {name} {h} 跳以内的公司 {n} 家", "{name} から {h} ホップ以内の企業 {n}社"],
  "Focus:": ["포커스:", "焦点：", "フォーカス："],
  "{n} neighbor": ["인접 기업 {n}개", "{n} 个相邻公司", "隣接企業 {n}社"],
  "{n} neighbors": ["인접 기업 {n}개", "{n} 个相邻公司", "隣接企業 {n}社"],
  "Esc to exit": ["Esc로 종료", "按 Esc 退出", "Esc で終了"],
  "Node color = the company's primary layer": ["노드 색상 = 기업의 주 레이어", "节点颜色 = 公司的主要层级", "ノードの色 = 企業の主レイヤー"],
  // ── NodePanel ────────────────────────────────────────────────────────────
  "Revenue / growth": ["매출 / 성장", "营收 / 增长", "売上高 / 成長"],
  "Guidance": ["가이던스", "业绩指引", "ガイダンス"],
  "Backlog / B2B": ["수주잔고 / B2B", "积压订单 / B2B", "受注残 / B2B"],
  "Supply status": ["공급 상황", "供应状况", "供給状況"],
  "Next catalyst": ["다음 촉매", "下一个催化因素", "次のカタリスト"],
  "{n} deal": ["거래 {n}건", "{n} 笔交易", "取引 {n}件"],
  "{n} deals": ["거래 {n}건", "{n} 笔交易", "取引 {n}件"],
  "latest {date}": ["최근 {date}", "最新 {date}", "最新 {date}"],
  "Show fewer": ["간략히 보기", "收起", "表示を減らす"],
  "+{n} more deal": ["+{n}건 더 보기", "再显示 {n} 笔", "+{n}件をさらに表示"],
  "+{n} more deals": ["+{n}건 더 보기", "再显示 {n} 笔", "+{n}件をさらに表示"],
  "from chain: {chain}": ["출처 체인: {chain}", "来源产业链：{chain}", "出典チェーン：{chain}"],
  "not a graph node": ["그래프 노드 아님", "非图谱节点", "グラフのノードではない"],
  "{n} entry": ["항목 {n}개", "{n} 条记录", "{n}件"],
  "{n} entries": ["항목 {n}개", "{n} 条记录", "{n}件"],
  "Close (Esc)": ["닫기 (Esc)", "关闭 (Esc)", "閉じる (Esc)"],
  "public": ["상장", "上市", "上場"],
  "private": ["비상장", "非上市", "非上場"],
  "subsidiary": ["자회사", "子公司", "子会社"],
  "stale": ["오래됨", "已过时", "古いデータ"],
  "no signals yet": ["아직 시그널 없음", "暂无信号", "シグナルはまだありません"],
  "Copy ticker": ["티커 복사", "复制代码", "ティッカーをコピー"],
  "copied": ["복사됨", "已复制", "コピーしました"],
  "Copy \"Transcript:{id}\" — the enrichment command for Claude Code": ["\"Transcript:{id}\" 복사 — Claude Code용 보강 명령", "复制 \"Transcript:{id}\" — Claude Code 的补充命令", "\"Transcript:{id}\" をコピー — Claude Code 用の拡充コマンド"],
  "Transcript": ["트랜스크립트", "会议纪要", "トランスクリプト"],
  "Hide Report": ["리포트 숨기기", "隐藏报告", "レポートを隠す"],
  "Stock Report": ["종목 리포트", "个股报告", "銘柄レポート"],
  "Download PDF": ["PDF 다운로드", "下载 PDF", "PDFをダウンロード"],
  "Loading report…": ["리포트 불러오는 중…", "正在加载报告…", "レポートを読み込み中…"],
  "⚡ Supply tight": ["⚡ 공급 부족", "⚡ 供应紧张", "⚡ 供給逼迫"],
  "📈 Guidance raised": ["📈 가이던스 상향", "📈 上调指引", "📈 ガイダンス引き上げ"],
  "📜 Long-term contracts": ["📜 장기 계약", "📜 长期合同", "📜 長期契約"],
  "🏗️ Capacity expanding": ["🏗️ 생산능력 확대", "🏗️ 产能扩张", "🏗️ 生産能力拡大"],
  "Generation exposure": ["세대별 익스포저", "世代敞口", "世代別エクスポージャー"],
  "B200 (Blackwell) → Vera Rubin": ["B200 (블랙웰) → 베라 루빈", "B200 (Blackwell) → Vera Rubin", "B200 (Blackwell) → Vera Rubin"],
  "MI355 → MI450 / Helios": ["MI355 → MI450 / Helios", "MI355 → MI450 / Helios", "MI355 → MI450 / Helios"],
  "Trainium2 → Trainium3": ["트레이니엄2 → 트레이니엄3", "Trainium2 → Trainium3", "Trainium2 → Trainium3"],
  "TPU v7 (Ironwood) → TPU v8 (v8t + v8i)": ["TPU v7 (Ironwood) → TPU v8 (v8t + v8i)", "TPU v7 (Ironwood) → TPU v8 (v8t + v8i)", "TPU v7 (Ironwood) → TPU v8 (v8t + v8i)"],
  "retained": ["유지", "保留", "維持"],
  "new entrant": ["신규 진입", "新进入者", "新規参入"],
  "not in next-gen chain (lost socket, or not yet added)": ["차세대 체인에 없음 (소켓 상실 또는 아직 미등록)", "不在下一代产业链中（失去份额，或尚未添加）", "次世代チェーンに不在（ソケット喪失、または未登録）"],
  "Product / Capacity Timeline": ["제품 / 생산능력 타임라인", "产品 / 产能时间线", "製品 / 生産能力タイムライン"],
  "Signals": ["시그널", "信号", "シグナル"],
  "Filter {n} signals…": ["시그널 {n}개 필터…", "筛选 {n} 条信号…", "{n}件のシグナルを絞り込み…"],
  "timeline topic: {topic}": ["타임라인 주제: {topic}", "时间线主题：{topic}", "タイムラインのトピック：{topic}"],
  "{n} of {total} signals match": ["시그널 {total}개 중 {n}개 일치", "{total} 条信号中有 {n} 条匹配", "{total}件中 {n}件のシグナルが一致"],
  "No signals match this filter.": ["이 필터와 일치하는 시그널이 없습니다.", "没有符合此筛选条件的信号。", "このフィルターに一致するシグナルはありません。"],
  "Show {n} more ({hidden} hidden)": ["{n}개 더 보기 ({hidden}개 숨김)", "再显示 {n} 条（隐藏 {hidden} 条）", "さらに{n}件表示（{hidden}件非表示）"],
  "Show less": ["접기", "收起", "表示を減らす"],
  "Customers": ["고객", "客户", "顧客"],
  "Suppliers": ["공급사", "供应商", "サプライヤー"],
  "show fewer": ["접기", "收起", "表示を減らす"],
  "+{n} more": ["+{n}개 더", "再显示 {n} 个", "+{n}件"],
  "Customers & suppliers on file": ["기록된 고객 및 공급사", "已记录的客户与供应商", "記録上の顧客とサプライヤー"],
  "named in this company's filings / calls, not graph nodes": ["이 기업의 공시·실적 발표에 언급된 곳으로, 그래프 노드는 아님", "在该公司的公告/电话会议中提及，但不是图谱节点", "この企業の開示書類・説明会で言及されたが、グラフのノードではない"],
  "none on file": ["기록 없음", "暂无记录", "記録なし"],
  // NodePanel "At a glance" card + collapsed lists (2026-10-01)
  "At a glance": ["한눈에 보기", "概览", "概要"],
  "Hide details": ["내용 접기", "收起详情", "詳細を隠す"],
  "Top customers": ["주요 고객", "主要客户", "主要顧客"],
  "Top suppliers": ["주요 공급사", "主要供应商", "主要サプライヤー"],
  "top {n} of {total}": ["{total}곳 중 상위 {n}곳", "{total} 家中前 {n} 家", "{total}社中上位{n}社"],
  "Show all ({n})": ["전체 보기 ({n})", "显示全部（{n}）", "すべて表示（{n}）"],
  // ── Evidence / CompanyLink / ReportView / report page ────────────────────
  "Source text is not on disk for this label": ["이 라벨의 원문이 저장되어 있지 않습니다", "该标签的原文未保存", "このラベルの原文は保存されていません"],
  "Number not found in source — flagged for review": ["원문에서 수치를 찾지 못함 — 검토 대상으로 표시", "原文中未找到该数字 — 已标记待审核", "原文に数値が見つかりません — 要確認として表示"],
  "Number located in the source text": ["원문에서 수치 확인됨", "已在原文中找到该数字", "原文で数値を確認"],
  "Counterparty named in the source text (no number to check)": ["원문에 거래 상대방 언급됨 (확인할 수치 없음)", "原文中提及交易对手（无可核对的数字）", "原文に取引相手の記載あり（確認する数値なし）"],
  "Signal wording located in the source text (no number to check)": ["원문에서 시그널 문구 확인됨 (확인할 수치 없음)", "已在原文中找到该信号表述（无可核对的数字）", "原文でシグナルの記述を確認（確認する数値なし）"],
  "Not found in source:": ["원문에 없음:", "原文中未找到：", "原文に見つからない："],
  "Nearest passage:": ["가장 가까운 구절:", "最接近的段落：", "最も近い箇所："],
  "Show the source passage": ["원문 구절 보기", "显示原文段落", "原文の該当箇所を表示"],
  "source": ["출처", "出处", "出典"],
  "Source evidence": ["출처 근거", "出处依据", "出典の根拠"],
  "Loading source…": ["출처 불러오는 중…", "正在加载出处…", "出典を読み込み中…"],
  "No evidence record for this entry yet — run evidence.py and sync.": ["이 항목에 대한 근거 기록이 아직 없습니다 — evidence.py 실행 후 동기화하세요.", "该条目暂无依据记录 — 请运行 evidence.py 并同步。", "この項目の根拠記録はまだありません — evidence.py を実行して同期してください。"],
  "{n} located": ["{n}건 확인", "{n} 条已找到", "{n}件確認"],
  "{n} flagged": ["{n}건 검토 필요", "{n} 条已标记", "{n}件要確認"],
  "{n} no source text": ["{n}건 원문 없음", "{n} 条无原文", "{n}件原文なし"],
  "{n} not indexed": ["{n}건 미색인", "{n} 条未索引", "{n}件未索引"],
  "Sources:": ["출처:", "出处：", "出典："],
  "Open {name}": ["{name} 열기", "打开 {name}", "{name} を開く"],
  "Equity Research": ["기업 분석 리포트", "股票研究", "株式リサーチ"],
  "Print / Save as PDF": ["인쇄 / PDF로 저장", "打印 / 另存为 PDF", "印刷 / PDFとして保存"],
  "Loading…": ["불러오는 중…", "加载中…", "読み込み中…"],
  "No report found for {name}.": ["{name}에 대한 리포트가 없습니다.", "未找到 {name} 的报告。", "{name} のレポートは見つかりませんでした。"],
  // ── Chain 2D (component + lib/chain2d.ts renderer) ───────────────────────
  "{n} contract": ["계약 {n}건", "{n} 份合同", "契約 {n}件"],
  "{n} contracts": ["계약 {n}건", "{n} 份合同", "契約 {n}件"],
  "{n} signal": ["시그널 {n}개", "{n} 条信号", "シグナル {n}件"],
  "{n} signals": ["시그널 {n}개", "{n} 条信号", "シグナル {n}件"],
  "{n} company": ["기업 {n}개", "{n} 家公司", "{n}社"],
  "{n} companies": ["기업 {n}개", "{n} 家公司", "{n}社"],
  "supply relationship": ["공급 관계", "供应关系", "供給関係"],
  "latest:": ["최근:", "最新：", "最新："],
  "click = detail": ["클릭 = 상세", "点击 = 详情", "クリック = 詳細"],
  "Expand {name}": ["{name} 펼치기", "展开 {name}", "{name} を展開"],
  "Collapse {name}": ["{name} 접기", "折叠 {name}", "{name} を折りたたむ"],
  "collapsed": ["접힘", "已折叠", "折りたたみ中"],
  "appears in another chain": ["다른 체인에 등장", "出现在其他产业链中", "別のチェーンに登場"],
  "{n} contract on this link": ["이 연결의 계약 {n}건", "此连线上有 {n} 份合同", "このリンクの契約 {n}件"],
  "{n} contracts on this link": ["이 연결의 계약 {n}건", "此连线上有 {n} 份合同", "このリンクの契約 {n}件"],
  "Structure only — no deal/contract data on this link yet.": ["구조만 있음 — 이 연결에는 아직 거래·계약 데이터가 없습니다.", "仅有结构 — 此连线暂无交易/合同数据。", "構造のみ — このリンクにはまだ取引・契約データがありません。"],
  "{companies} collapsed — click to expand": ["{companies} 접힘 — 클릭해서 펼치기", "{companies}已折叠 — 点击展开", "{companies}を折りたたみ中 — クリックで展開"],
  "{companies} collapsed": ["{companies} 접힘", "{companies}已折叠", "{companies}を折りたたみ中"],
  "click = expand": ["클릭 = 펼치기", "点击 = 展开", "クリック = 展開"],
  "External — appears in another chain, not part of this chain's structure": ["외부 — 다른 체인에 등장하며 이 체인의 구조에는 속하지 않음", "外部 — 出现在其他产业链中，不属于本产业链结构", "外部 — 別のチェーンに登場し、このチェーンの構造には含まれない"],
  "downstream": ["하류", "下游", "川下"],
  "upstream": ["상류", "上游", "川上"],
  "click = unpin": ["클릭 = 고정 해제", "点击 = 取消固定", "クリック = 固定解除"],
  "click = pin path": ["클릭 = 경로 고정", "点击 = 固定路径", "クリック = 経路を固定"],
  "Esc = unpin": ["Esc = 고정 해제", "Esc = 取消固定", "Esc = 固定解除"],
  "External": ["외부", "外部", "外部"],
  "Chain": ["체인", "产业链", "チェーン"],
  "All value chains (everything)": ["전체 밸류체인 (모두)", "全部价值链（全部）", "すべてのバリューチェーン（全体）"],
  "All value chains": ["전체 밸류체인", "全部价值链", "すべてのバリューチェーン"],
  "every company & edge, grouped by layer": ["모든 기업과 연결을 레이어별로 묶어 표시", "所有公司与连线，按层级分组", "すべての企業とエッジをレイヤー別に表示"],
  "Map legend": ["지도 범례", "地图图例", "マップの凡例"],
  "earnings data": ["실적 데이터", "业绩数据", "決算データ"],
  "deal data": ["거래 데이터", "交易数据", "取引データ"],
  "structure only": ["구조만", "仅结构", "構造のみ"],
  "Named as a supplier or customer here, but its own node lives in another chain": ["여기서는 공급사나 고객으로 언급되지만 자체 노드는 다른 체인에 있음", "在此被列为供应商或客户，但其节点位于其他产业链", "ここではサプライヤーまたは顧客として登場するが、自身のノードは別のチェーンにある"],
  "external = appears in another chain": ["외부 = 다른 체인에 등장", "外部 = 出现在其他产业链", "外部 = 別のチェーンに登場"],
  "hover = full path · click = pin (click again / Esc = unpin) · click edge = contracts · layer label = collapse": ["마우스 오버 = 전체 경로 · 클릭 = 고정 (다시 클릭 / Esc = 해제) · 연결선 클릭 = 계약 · 레이어 이름 = 접기", "悬停 = 完整路径 · 点击 = 固定（再次点击 / Esc = 取消）· 点击连线 = 合同 · 层级标签 = 折叠", "ホバー = 全経路 · クリック = 固定（再クリック / Esc = 解除）· エッジをクリック = 契約 · レイヤー名 = 折りたたみ"],
  "Draw every layer as one bar — edges between layers stay visible": ["모든 레이어를 막대 하나로 표시 — 레이어 간 연결선은 계속 보임", "将每个层级绘制为一条横条 — 层级之间的连线仍可见", "各レイヤーを1本のバーで表示 — レイヤー間のエッジは表示されたまま"],
  "Collapse all": ["모두 접기", "全部折叠", "すべて折りたたむ"],
  "Expand all": ["모두 펼치기", "全部展开", "すべて展開"],
  "Building the map…": ["지도를 만드는 중…", "正在生成地图…", "マップを作成中…"],
  "Could not load this chain ({err}). Pick another chain above.": ["이 체인을 불러오지 못했습니다 ({err}). 위에서 다른 체인을 선택하세요.", "无法加载该产业链（{err}）。请在上方选择其他产业链。", "このチェーンを読み込めませんでした（{err}）。上で別のチェーンを選んでください。"],
  "{c} companies · {e} edges across all chains": ["기업 {c}개 · 전체 체인의 연결 {e}개", "{c} 家公司 · 全部产业链共 {e} 条连线", "{c}社 · 全チェーンのエッジ {e}本"],
  "{c} companies · {e} edges in this chain": ["기업 {c}개 · 이 체인의 연결 {e}개", "{c} 家公司 · 本产业链 {e} 条连线", "{c}社 · このチェーンのエッジ {e}本"],
  "{n} layer collapsed": ["레이어 {n}개 접힘", "{n} 个层级已折叠", "{n}レイヤーを折りたたみ中"],
  "{n} layers collapsed": ["레이어 {n}개 접힘", "{n} 个层级已折叠", "{n}レイヤーを折りたたみ中"],
  // ── Generations ──────────────────────────────────────────────────────────
  "Retained": ["유지", "保留", "維持"],
  "in both generations — watch the content delta": ["두 세대 모두 참여 — 탑재 콘텐츠 변화에 주목", "两代均参与 — 关注含量变化", "両世代に参加 — 搭載内容の変化に注目"],
  "New in next gen": ["차세대 신규", "下一代新进", "次世代で新規"],
  "won a socket it didn't have in the current generation": ["현 세대에는 없던 소켓을 확보", "赢得了本代没有的份额（socket）", "現世代にはなかったソケットを獲得"],
  "Not in next gen": ["차세대에 없음", "未进入下一代", "次世代に不在"],
  "lost the socket — or not yet added to the new chain": ["소켓 상실 — 또는 아직 새 체인에 미등록", "失去份额 — 或尚未加入新产业链", "ソケット喪失 — または新チェーンに未登録"],
  "Generation Transitions": ["세대 전환", "代际转换", "世代移行"],
  "Who keeps, gains, or loses a socket when an accelerator platform moves to its next generation — and how the content changes (HBM3E → HBM4, copper → optical, …). Computed from the curated chains; click a company for details.": ["가속기 플랫폼이 다음 세대로 넘어갈 때 누가 소켓을 유지·확보·상실하는지, 그리고 탑재 콘텐츠가 어떻게 바뀌는지(HBM3E → HBM4, 구리 → 광 …) 보여줍니다. 큐레이션된 체인에서 계산하며, 기업을 클릭하면 상세 정보가 열립니다.", "当加速器平台升级到下一代时，谁保留、赢得或失去份额（socket），以及含量如何变化（HBM3E → HBM4、铜 → 光……）。基于人工整理的产业链计算；点击公司查看详情。", "アクセラレーター・プラットフォームが次世代へ移行する際に、どの企業がソケットを維持・獲得・喪失するか、そして搭載内容がどう変わるか（HBM3E → HBM4、銅 → 光 …）を示します。キュレーションされたチェーンから算出。企業をクリックすると詳細を表示。"],
  "{n} companies across both generations.": ["두 세대에 걸친 기업 {n}개.", "两代共涉及 {n} 家公司。", "両世代にまたがる企業 {n}社。"],
  "none": ["없음", "无", "なし"],
  // ── CellText / Timelines ─────────────────────────────────────────────────
  "Collapse {label} for {subject}": ["{subject}의 {label} 접기", "折叠 {subject} 的 {label}", "{subject} の {label} を折りたたむ"],
  "Show full {label} for {subject}": ["{subject}의 {label} 전체 보기", "显示 {subject} 的完整 {label}", "{subject} の {label} をすべて表示"],
  "Collapse {label}": ["{label} 접기", "折叠 {label}", "{label} を折りたたむ"],
  "Show full {label}": ["{label} 전체 보기", "显示完整 {label}", "{label} をすべて表示"],
  "Click to collapse": ["클릭해서 접기", "点击折叠", "クリックで折りたたむ"],
  "Close": ["닫기", "关闭", "閉じる"],
  "Full signal": ["전체 시그널", "完整信号", "シグナル全文"],
  "Source": ["출처", "来源", "出典"],
  "Transitions": ["세대 전환", "代际转换", "世代移行"],
  "Supply": ["공급", "供应", "供給"],
  "Optical": ["광", "光通信", "光"],
  "Compute": ["컴퓨팅", "计算", "コンピュート"],
  "Manufacturing": ["제조", "制造", "製造"],
  "Infrastructure": ["인프라", "基础设施", "インフラ"],
  "Products": ["제품", "产品", "製品"],
  "30d": ["30일", "30 天", "30日"],
  "90d": ["90일", "90 天", "90日"],
  "180d": ["180일", "180 天", "180日"],
  "Technology & Product Timelines": ["기술·제품 타임라인", "技术与产品时间线", "技術・製品タイムライン"],
  "Forward market-size, adoption and launch views — when each technology ramps, how big it gets, and which models adopt it. Curated tables are hand-maintained; the auto-derived table under each topic is generated from the graph's latest signals.": ["향후 시장 규모·채택·출시 전망 — 각 기술이 언제 본격화되고 얼마나 커지며 어떤 모델이 채택하는지. 큐레이션 표는 수작업으로 관리하며, 주제별 자동 생성 표는 그래프의 최신 시그널로 만들어집니다.", "前瞻性的市场规模、采用与发布视图 — 每项技术何时放量、规模多大、哪些型号采用。人工整理的表格为手动维护；每个主题下的自动生成表格来自图谱的最新信号。", "今後の市場規模・採用・投入の見通し — 各技術がいつ立ち上がり、どれほど大きくなり、どのモデルが採用するか。キュレーション表は手作業で管理し、各トピックの自動生成表はグラフの最新シグナルから作られます。"],
  "Timeline topics": ["타임라인 주제", "时间线主题", "タイムラインのトピック"],
  "{c} curated rows · {a} auto-derived signals": ["큐레이션 행 {c}개 · 자동 생성 시그널 {a}개", "人工整理 {c} 行 · 自动生成信号 {a} 条", "キュレーション {c}行 · 自動生成シグナル {a}件"],
  "Search this topic": ["이 주제 검색", "搜索本主题", "このトピックを検索"],
  "Company, product, figure… (matches every table below)": ["기업, 제품, 수치… (아래 모든 표에서 검색)", "公司、产品、数字…（匹配下方所有表格）", "企業、製品、数値…（下のすべての表を検索）"],
  "Auto-derived rows since": ["자동 생성 행 기간", "自动生成行的时间范围", "自動生成行の期間"],
  "Show auto-derived rows since": ["자동 생성 행 표시 기간", "显示此后的自动生成行", "自動生成行の表示期間"],
  "Group the auto-derived rows under each company": ["자동 생성 행을 기업별로 묶기", "按公司对自动生成行分组", "自動生成行を企業ごとにまとめる"],
  "Group by company": ["기업별 묶기", "按公司分组", "企業別にまとめる"],
  "Copy the visible auto-derived rows as CSV": ["표시된 자동 생성 행을 CSV로 복사", "将可见的自动生成行复制为 CSV", "表示中の自動生成行をCSVでコピー"],
  "Copied ✓": ["복사됨 ✓", "已复制 ✓", "コピー済み ✓"],
  "Copy failed": ["복사 실패", "复制失败", "コピー失敗"],
  "Copy CSV": ["CSV 복사", "复制 CSV", "CSVをコピー"],
  "Download the visible auto-derived rows as a CSV file": ["표시된 자동 생성 행을 CSV 파일로 다운로드", "将可见的自动生成行下载为 CSV 文件", "表示中の自動生成行をCSVファイルでダウンロード"],
  "Download CSV": ["CSV 다운로드", "下载 CSV", "CSVをダウンロード"],
  "Source:": ["출처:", "来源：", "出典："],
  "Latest graph signals": ["그래프 최신 시그널", "图谱最新信号", "グラフの最新シグナル"],
  "Table": ["표", "表格", "表"],
  "Auto-derived from graph": ["그래프에서 자동 생성", "由图谱自动生成", "グラフから自動生成"],
  "Curated": ["큐레이션", "人工整理", "キュレーション"],
  "{n} rows": ["{n}행", "{n} 行", "{n}行"],
  "{n} of {total} rows": ["{total}행 중 {n}행", "{total} 行中的 {n} 行", "{total}行中 {n}行"],
  "No rows match": ["일치하는 행이 없습니다", "没有匹配的行", "一致する行はありません"],
  "in the last {n} days": ["(최근 {n}일)", "（最近 {n} 天内）", "（直近{n}日間）"],
  "Sort by {col}": ["{col} 기준 정렬", "按 {col} 排序", "{col} で並べ替え"],
  // ── lib/table.ts + Screener ──────────────────────────────────────────────
  "Fresh (≤45d)": ["최신 (≤45일)", "新鲜（≤45 天）", "新しい（≤45日）"],
  "Aging (46–120d)": ["노후화 (46–120일)", "渐旧（46–120 天）", "やや古い（46–120日）"],
  "Stale (>120d)": ["오래됨 (>120일)", "过时（>120 天）", "古い（>120日）"],
  "No date": ["날짜 없음", "无日期", "日付なし"],
  "today": ["오늘", "今天", "今日"],
  "{n}d ago": ["{n}일 전", "{n} 天前", "{n}日前"],
  "Company": ["기업", "公司", "企業"],
  "Ticker": ["티커", "代码", "ティッカー"],
  "Exchange": ["거래소", "交易所", "取引所"],
  "Layer": ["레이어", "层级", "レイヤー"],
  "Growth": ["성장", "增长", "成長"],
  "As of": ["기준일", "截至", "基準日"],
  "Company Screener": ["기업 스크리너", "公司筛选器", "企業スクリーナー"],
  "Headline operational metrics per company — no share prices, just signals. Filter by layer, sector, chain or text; click a column header to sort. The \"As of\" colour is the age of the source call: green ≤{fresh} days, amber ≤{aging}, red older.": ["기업별 핵심 영업 지표 — 주가가 아닌 시그널만 보여줍니다. 레이어·섹터·체인·텍스트로 필터링하고, 열 제목을 클릭해 정렬하세요. \"기준일\" 색상은 출처 실적 발표의 경과 기간입니다: 초록 ≤{fresh}일, 주황 ≤{aging}일, 빨강은 그보다 오래됨.", "每家公司的核心经营指标 — 不含股价，只有信号。可按层级、板块、产业链或文字筛选；点击列标题排序。“截至”的颜色表示来源电话会议的时效：绿色 ≤{fresh} 天，琥珀色 ≤{aging} 天，红色更早。", "企業ごとの主要な事業指標 — 株価ではなくシグナルのみ。レイヤー・セクター・チェーン・テキストで絞り込み、列見出しをクリックで並べ替え。「基準日」の色は出典となった説明会の経過日数：緑 ≤{fresh}日、黄 ≤{aging}日、赤はそれ以前。"],
  "Layer / Domain": ["레이어 / 도메인", "层级 / 领域", "レイヤー / ドメイン"],
  "Sector": ["섹터", "板块", "セクター"],
  "Search": ["검색", "搜索", "検索"],
  "Company, ticker, or any word in the metrics…": ["기업, 티커 또는 지표 속 단어…", "公司、代码或指标中的任意词…", "企業、ティッカー、または指標内の語句…"],
  "Hide companies whose latest source is older than {n} days": ["최신 출처가 {n}일보다 오래된 기업 숨기기", "隐藏最新来源早于 {n} 天的公司", "最新の出典が{n}日より古い企業を非表示"],
  "Hide stale": ["오래된 항목 숨기기", "隐藏过时项", "古い項目を非表示"],
  "Show or hide columns": ["열 표시/숨기기", "显示或隐藏列", "列の表示・非表示"],
  "Columns": ["열", "列", "列"],
  "Reset to default": ["기본값으로 초기화", "恢复默认", "既定に戻す"],
  "Copy the visible rows' tickers as a comma-separated list (for a watchlist)": ["표시된 행의 티커를 쉼표로 구분해 복사 (관심 종목용)", "将可见行的代码复制为逗号分隔列表（用于自选股）", "表示中の行のティッカーをカンマ区切りでコピー（ウォッチリスト用）"],
  "Copy tickers ({n})": ["티커 복사 ({n})", "复制代码（{n}）", "ティッカーをコピー（{n}）"],
  "Copy the visible rows as CSV": ["표시된 행을 CSV로 복사", "将可见行复制为 CSV", "表示中の行をCSVでコピー"],
  "Download the visible rows as a CSV file": ["표시된 행을 CSV 파일로 다운로드", "将可见行下载为 CSV 文件", "表示中の行をCSVファイルでダウンロード"],
  "Showing {n} of {total} companies": ["기업 {total}개 중 {n}개 표시", "显示 {total} 家公司中的 {n} 家", "{total}社中 {n}社を表示"],
  "{n} stale hidden": ["오래된 {n}개 숨김", "已隐藏 {n} 家过时公司", "古い{n}社を非表示"],
  "Freshness of the visible rows": ["표시된 행의 최신성", "可见行的时效", "表示中の行の鮮度"],
  "{n} fresh": ["최신 {n}", "新鲜 {n}", "新しい {n}"],
  "{n} aging": ["노후화 {n}", "渐旧 {n}", "やや古い {n}"],
  "{n} stale": ["오래됨 {n}", "过时 {n}", "古い {n}"],
  "No companies match the current filters.": ["현재 필터와 일치하는 기업이 없습니다.", "没有符合当前筛选条件的公司。", "現在のフィルターに一致する企業はありません。"],
  "{label} — source dated {date} ({age})": ["{label} — 출처 일자 {date} ({age})", "{label} — 来源日期 {date}（{age}）", "{label} — 出典日 {date}（{age}）"],
  "No source date": ["출처 일자 없음", "无来源日期", "出典日なし"],
  "{n} companies shown · {total} total in company_metrics.json · exports include the visible rows only": ["기업 {n}개 표시 · company_metrics.json 전체 {total}개 · 내보내기는 표시된 행만 포함", "显示 {n} 家公司 · company_metrics.json 共 {total} 家 · 导出仅包含可见行", "{n}社を表示 · company_metrics.json 全{total}社 · エクスポートは表示中の行のみ"],
  // ── Picks / PicksUniverse / lib/picks.ts ─────────────────────────────────
  "Basket": ["바스켓", "组合", "バスケット"],
  "US 15": ["미국 15", "美股 15", "米国15"],
  "US + Korea 15": ["미국 + 한국 15", "美股 + 韩股 15", "米国 + 韓国15"],
  "Ranked from every US-listed company in the graph (178 names).": ["그래프 내 모든 미국 상장 기업(178개 종목) 중에서 순위를 매겼습니다.", "从图谱中所有美国上市公司（178 只）中排名选出。", "グラフ内のすべての米国上場企業（178銘柄）からランク付け。"],
  "The same screen run across 178 US-listed and 35 Korea-listed names (213 total).": ["같은 스크리닝을 미국 상장 178개와 한국 상장 35개 종목(총 213개)에 적용했습니다.", "同一筛选应用于 178 只美国上市和 35 只韩国上市股票（共 213 只）。", "同じスクリーニングを米国上場178銘柄と韓国上場35銘柄（計213銘柄）に適用。"],
  "Market open": ["장 중", "开市中", "取引時間中"],
  "Market closed": ["장 마감", "已收市", "取引時間外"],
  "updated {time}": ["{time} 업데이트", "{time} 更新", "{time} 更新"],
  "Refreshing…": ["새로 고치는 중…", "刷新中…", "更新中…"],
  "Refresh": ["새로 고침", "刷新", "更新"],
  "Entry price is the {date} close; every return below is measured against it and updates while the market is open.": ["진입가는 {date} 종가이며, 아래의 모든 수익률은 이를 기준으로 계산되고 장 중에 갱신됩니다.", "建仓价为 {date} 收盘价；下方所有收益率均以此为基准，并在开市期间实时更新。", "エントリー価格は{date}の終値です。以下のリターンはすべてこれを基準に算出し、取引時間中に更新されます。"],
  "We couldn't reach the quote feed.": ["시세 피드에 연결하지 못했습니다.", "无法连接行情数据源。", "株価フィードに接続できませんでした。"],
  "The entry prices below are unaffected. Try again in a moment.": ["아래 진입가에는 영향이 없습니다. 잠시 후 다시 시도하세요.", "下方的建仓价不受影响。请稍后重试。", "以下のエントリー価格には影響ありません。しばらくしてから再試行してください。"],
  "Loading live prices…": ["실시간 시세 불러오는 중…", "正在加载实时价格…", "リアルタイム株価を読み込み中…"],
  "Basket return": ["바스켓 수익률", "组合收益率", "バスケットのリターン"],
  "equal weight · {n} of {total} priced": ["동일 가중 · {total}개 중 {n}개 시세 반영", "等权重 · {total} 只中 {n} 只已计价", "均等加重 · {total}銘柄中 {n}銘柄の価格を反映"],
  "Up / down": ["상승 / 하락", "上涨 / 下跌", "上昇 / 下落"],
  "since {date}": ["{date} 이후", "自 {date} 起", "{date}以降"],
  "Best": ["최고", "最佳", "最高"],
  "Worst": ["최저", "最差", "最低"],
  "Entry ({date})": ["진입가 ({date})", "建仓价（{date}）", "エントリー（{date}）"],
  "Last": ["현재가", "最新价", "現在値"],
  "vs entry": ["진입가 대비", "较建仓价", "エントリー比"],
  "Day": ["일간", "当日", "日次"],
  "Why it is on the list": ["선정 이유", "入选理由", "選定理由"],
  "Click any row to open that company's panel — live chart, the signals on file, and its place in the supply chain. Korean names are measured in won, so the basket return ignores the currency move. Research, not investment advice.": ["행을 클릭하면 해당 기업 패널이 열립니다 — 실시간 차트, 기록된 시그널, 공급망 내 위치. 한국 종목은 원화 기준이므로 바스켓 수익률에는 환율 변동이 반영되지 않습니다. 리서치 자료이며 투자 권유가 아닙니다.", "点击任意一行即可打开该公司的面板 — 实时图表、已记录的信号以及其在供应链中的位置。韩国股票以韩元计价，因此组合收益率不含汇率变动。仅供研究，不构成投资建议。", "行をクリックするとその企業のパネルが開きます — リアルタイムチャート、記録済みのシグナル、サプライチェーン上の位置。韓国銘柄はウォン建てのため、バスケットのリターンには為替変動が含まれません。リサーチであり、投資助言ではありません。"],
  "Hide all {n} screened companies": ["스크리닝한 {n}개 기업 전체 숨기기", "隐藏全部 {n} 家筛选公司", "スクリーニングした全{n}社を隠す"],
  "Show all {n} screened companies": ["스크리닝한 {n}개 기업 전체 보기", "显示全部 {n} 家筛选公司", "スクリーニングした全{n}社を表示"],
  "We couldn't load the screened list. Try again in a moment.": ["스크리닝 목록을 불러오지 못했습니다. 잠시 후 다시 시도하세요.", "无法加载筛选列表。请稍后重试。", "スクリーニング一覧を読み込めませんでした。しばらくしてから再試行してください。"],
  "Loading the full list…": ["전체 목록 불러오는 중…", "正在加载完整列表…", "全一覧を読み込み中…"],
  "Every company the screen scored, best first. Score is the 0–10 one-quarter rating; Off high is how far the stock sat below its 6-month high at the {date} close.": ["스크리닝에서 점수를 받은 모든 기업을 높은 순으로 표시합니다. 점수는 한 분기 기준 0–10점 평가이며, 고점 대비는 {date} 종가 기준 주가가 6개월 고점보다 얼마나 낮았는지입니다.", "筛选打分的所有公司，按得分从高到低排列。得分为一个季度的 0–10 分评级；距高点表示 {date} 收盘时股价低于其 6 个月高点的幅度。", "スクリーニングで採点したすべての企業を高い順に表示。スコアは1四半期の0–10点評価、高値比は{date}終値時点で株価が6カ月高値をどれだけ下回っていたかです。"],
  "Pricing {n} of {total}…": ["{total}개 중 {n}개 시세 반영 중…", "正在计价 {total} 只中的 {n} 只…", "{total}銘柄中 {n}銘柄の価格を取得中…"],
  "Score": ["점수", "得分", "スコア"],
  "Off high": ["고점 대비", "距高点", "高値比"],
  "Q3 guided +40% QoQ at ~72% gross margin; Scorpio X engagements went from 10 to the high teens.": ["3분기 가이던스 전분기 대비 +40%, 매출총이익률 약 72%; Scorpio X 고객 프로젝트가 10건에서 10건대 후반으로 증가.", "第三季度指引环比 +40%，毛利率约 72%；Scorpio X 客户项目从 10 个增至接近 20 个。", "第3四半期ガイダンスは前四半期比+40%、粗利益率約72%。Scorpio X の案件は10件から10件台後半に増加。"],
  "FQ4 guided +23% QoQ; book-to-bill a record 1.6 (1.3 → 1.5 → 1.6); operating margin 31.5% → ~37%.": ["회계 4분기 가이던스 전분기 대비 +23%; 수주 대비 출하 비율 사상 최고 1.6 (1.3 → 1.5 → 1.6); 영업이익률 31.5% → 약 37%.", "第四财季指引环比 +23%；订单出货比创纪录达 1.6（1.3 → 1.5 → 1.6）；营业利润率 31.5% → 约 37%。", "第4会計四半期ガイダンスは前四半期比+23%。BBレシオは過去最高の1.6（1.3 → 1.5 → 1.6）。営業利益率は31.5% → 約37%。"],
  "Guided +45% YoY; the vast majority of 2027 is under LTA; revenue is gated by supply, not demand.": ["전년 대비 +45% 가이던스; 2027년 물량 대부분이 장기공급계약(LTA)으로 확보; 매출은 수요가 아닌 공급에 의해 제한.", "指引同比 +45%；2027 年绝大部分已签长期协议（LTA）；营收受限于供应而非需求。", "前年比+45%のガイダンス。2027年分の大半は長期契約（LTA）済み。売上は需要ではなく供給で制約。"],
  "Revenue +51% QoQ at 84.6% gross margin; eight multi-year agreements running out to five years.": ["매출 전분기 대비 +51%, 매출총이익률 84.6%; 최장 5년에 이르는 다년 계약 8건.", "营收环比 +51%，毛利率 84.6%；八份多年期协议，最长至五年。", "売上高は前四半期比+51%、粗利益率84.6%。最長5年に及ぶ複数年契約が8件。"],
  "Record $41.5B (+74% QoQ) at 84.9% gross margin; management calls 2027 tighter than 2026.": ["사상 최대 $41.5B (전분기 대비 +74%), 매출총이익률 84.9%; 경영진은 2027년 수급이 2026년보다 더 빡빡하다고 언급.", "创纪录的 $41.5B（环比 +74%），毛利率 84.9%；管理层称 2027 年供需比 2026 年更紧。", "過去最高の$41.5B（前四半期比+74%）、粗利益率84.9%。経営陣は2027年の需給は2026年より逼迫すると説明。"],
  "Q4 AI revenue guided +30% QoQ to $21.7B; FY27 AI ~$115B; 2027 wafers, memory and substrates locked in.": ["4분기 AI 매출 가이던스 전분기 대비 +30%인 $21.7B; FY27 AI 약 $115B; 2027년 웨이퍼·메모리·기판 확보 완료.", "第四季度 AI 营收指引环比 +30% 至 $21.7B；FY27 AI 约 $115B；2027 年晶圆、存储器和基板已锁定。", "第4四半期のAI売上ガイダンスは前四半期比+30%の$21.7B。FY27のAIは約$115B。2027年のウェハー・メモリ・基板は確保済み。"],
  "FY27 fully booked with take-or-pay LTAs; backlog runs through end-CY2027; next quarter guided +12% QoQ.": ["FY27 물량이 테이크오어페이(take-or-pay) LTA로 완판; 수주잔고는 2027년 말까지; 다음 분기 가이던스 전분기 대비 +12%.", "FY27 已通过照付不议（take-or-pay）长期协议全部订满；积压订单延续至 2027 年底；下季度指引环比 +12%。", "FY27はテイク・オア・ペイ型LTAで完売。受注残は2027年末まで。次四半期ガイダンスは前四半期比+12%。"],
  "Backlog $8.5B heading above $10B; FY27 guided to a minimum of 30% growth; components secured to 2029.": ["수주잔고 $8.5B, $10B 이상으로 증가 예상; FY27 최소 30% 성장 가이던스; 2029년까지 부품 확보.", "积压订单 $8.5B，预计将超过 $10B；FY27 指引增长至少 30%；零部件已锁定至 2029 年。", "受注残は$8.5Bで$10B超へ。FY27は最低30%成長のガイダンス。部品は2029年まで確保。"],
  "Q3 ~+39% QoQ and already permit-secured; indium phosphide substrates are the optical bottleneck.": ["3분기 전분기 대비 약 +39%, 이미 수출 허가 확보; 인듐인(InP) 기판이 광 부품의 병목.", "第三季度环比约 +39%，且已获得许可；磷化铟衬底是光通信的瓶颈。", "第3四半期は前四半期比約+39%で、既に許可を取得済み。リン化インジウム基板が光通信のボトルネック。"],
  "Six straight quarters of accelerating growth; guided +43% YoY; capacity going from $5.8B to $9.8B.": ["6분기 연속 성장 가속; 전년 대비 +43% 가이던스; 생산능력 $5.8B에서 $9.8B로 확대.", "连续六个季度增长加速；指引同比 +43%；产能从 $5.8B 扩至 $9.8B。", "6四半期連続で成長が加速。前年比+43%のガイダンス。生産能力は$5.8Bから$9.8Bへ。"],
  "Q3 guided +12% QoQ; book-to-bill 1.49; 90-day backlog +81%; data-centre revenue +91%.": ["3분기 가이던스 전분기 대비 +12%; 수주 대비 출하 비율 1.49; 90일 수주잔고 +81%; 데이터센터 매출 +91%.", "第三季度指引环比 +12%；订单出货比 1.49；90 天积压订单 +81%；数据中心营收 +91%。", "第3四半期ガイダンスは前四半期比+12%。BBレシオ1.49。90日受注残+81%。データセンター売上+91%。"],
  "Q3 guide implies semiconductor growth accelerating past +50% YoY, with visibility through 2027.": ["3분기 가이던스는 반도체 부문 성장이 전년 대비 +50% 이상으로 가속함을 시사하며, 2027년까지 가시성 확보.", "第三季度指引意味着半导体业务增长加速至同比 +50% 以上，可见度延续至 2027 年。", "第3四半期ガイダンスは半導体部門の成長が前年比+50%超へ加速することを示唆し、2027年まで見通しあり。"],
  "Revenue +115% YoY; management guided the shape of FY27 at +20% then +30% QoQ into the back half.": ["매출 전년 대비 +115%; 경영진은 FY27 흐름을 전분기 대비 +20%, 이어 하반기 +30%로 제시.", "营收同比 +115%；管理层给出 FY27 的走势：环比 +20%，下半年再 +30%。", "売上高は前年比+115%。経営陣はFY27の推移を前四半期比+20%、下期は+30%と説明。"],
  "Q3 guided +17% QoQ; enterprise data +45% QoQ; book-to-bill well above 1 and a $1B buyback.": ["3분기 가이던스 전분기 대비 +17%; 엔터프라이즈 데이터 전분기 대비 +45%; 수주 대비 출하 비율 1을 크게 상회, $1B 자사주 매입.", "第三季度指引环比 +17%；企业数据业务环比 +45%；订单出货比远高于 1，并有 $1B 回购。", "第3四半期ガイダンスは前四半期比+17%。エンタープライズデータは前四半期比+45%。BBレシオは1を大きく上回り、$1Bの自社株買い。"],
  "2026 growth guide raised three times — above 20%, then 30%, then approaching 40%.": ["2026년 성장 가이던스 세 차례 상향 — 20% 이상, 30%, 그리고 40%에 근접.", "2026 年增长指引三次上调 — 先是 20% 以上，然后 30%，再到接近 40%。", "2026年の成長ガイダンスを3回引き上げ — 20%超、30%、そして40%近くへ。"],
  "Q2 revenue +50.9% QoQ at a 76% operating margin with fabs at 100%; NVIDIA sees memory pricing rising into 2027.": ["2분기 매출 전분기 대비 +50.9%, 영업이익률 76%, 팹 가동률 100%; NVIDIA는 메모리 가격이 2027년까지 오를 것으로 전망.", "第二季度营收环比 +50.9%，营业利润率 76%，晶圆厂满载 100%；英伟达预计存储器价格上涨将延续至 2027 年。", "第2四半期の売上高は前四半期比+50.9%、営業利益率76%、工場稼働率100%。NVIDIAはメモリ価格が2027年にかけて上昇すると予想。"],
  "Three supply contracts starting 2027 (Si capacitor $1,035M, MLCC $294M, MLCC $779M); MLCC ASP +13.9%.": ["2027년 시작 공급계약 3건 (실리콘 커패시터 $1,035M, MLCC $294M, MLCC $779M); MLCC 평균판매가격 +13.9%.", "三份自 2027 年起的供货合同（硅电容 $1,035M、MLCC $294M、MLCC $779M）；MLCC 平均售价 +13.9%。", "2027年開始の供給契約3件（シリコンキャパシタ$1,035M、MLCC $294M、MLCC $779M）。MLCCの平均販売価格+13.9%。"],
  "Q2 revenue +28% QoQ at a 52% operating margin, memory at 100% utilisation; HBM4 above half of HBM from Q3.": ["2분기 매출 전분기 대비 +28%, 영업이익률 52%, 메모리 가동률 100%; 3분기부터 HBM4가 HBM의 절반 이상.", "第二季度营收环比 +28%，营业利润率 52%，存储器产能利用率 100%；自第三季度起 HBM4 占 HBM 一半以上。", "第2四半期の売上高は前四半期比+28%、営業利益率52%、メモリ稼働率100%。第3四半期からHBM4がHBMの半分超に。"],
  // ── CapexBacklog ─────────────────────────────────────────────────────────
  "Sort": ["정렬", "排序", "並べ替え"],
  "Sort {title} bars": ["{title} 막대 정렬", "对 {title} 条形排序", "{title} のバーを並べ替え"],
  "Value": ["값", "数值", "値"],
  "Name": ["이름", "名称", "名前"],
  "Copy these bars as CSV": ["이 막대들을 CSV로 복사", "将这些条形复制为 CSV", "これらのバーをCSVでコピー"],
  "Chart value:": ["차트 값:", "图表数值：", "チャートの値："],
  "Growth:": ["성장:", "增长：", "成長："],
  "Failed to load capex_backlog.json — run": ["capex_backlog.json을 불러오지 못했습니다 — 다음을 실행하세요:", "capex_backlog.json 加载失败 — 请运行", "capex_backlog.json を読み込めませんでした — 次を実行してください："],
  "Loading capex & backlog…": ["설비투자·수주잔고 불러오는 중…", "正在加载资本开支与积压订单…", "設備投資・受注残を読み込み中…"],
  "Capex & Backlog": ["설비투자·수주잔고", "资本开支与积压订单", "設備投資・受注残"],
  "What the AI buildout's buyers spend (capex — the demand signal for every supplier below them) and what they have already sold (backlog / RPO / contracted revenue). Hyperscalers and neoclouds, from earnings sources only. Updated {date}.": ["AI 인프라 구축의 구매자들이 얼마나 지출하는지(설비투자 — 그 아래 모든 공급사의 수요 시그널)와 이미 얼마나 판매했는지(수주잔고 / RPO / 계약 매출). 하이퍼스케일러와 네오클라우드, 실적 자료만 사용. {date} 업데이트.", "AI 基础设施建设的买方花了多少（资本开支 — 其下游所有供应商的需求信号），以及已经卖出多少（积压订单 / RPO / 已签约收入）。涵盖超大规模云厂商和新兴云，仅基于业绩资料。{date} 更新。", "AI インフラ構築の買い手がどれだけ支出しているか（設備投資 — その下のすべてのサプライヤーにとっての需要シグナル）と、既にどれだけ販売しているか（受注残 / RPO / 契約済み売上）。ハイパースケーラーとネオクラウド、決算資料のみに基づく。{date} 更新。"],
  "{n} companies across {g} tables": ["표 {g}개에 걸친 기업 {n}개", "{g} 个表格中的 {n} 家公司", "{g}個の表にわたる{n}社"],
  "Copy every table below as one CSV": ["아래 모든 표를 하나의 CSV로 복사", "将下方所有表格复制为一个 CSV", "下のすべての表を1つのCSVでコピー"],
  "Copy table as CSV": ["표를 CSV로 복사", "将表格复制为 CSV", "表をCSVでコピー"],
  "Download every table below as one CSV file": ["아래 모든 표를 하나의 CSV 파일로 다운로드", "将下方所有表格下载为一个 CSV 文件", "下のすべての表を1つのCSVファイルでダウンロード"],
  "Capex (latest qtr)": ["설비투자 (최근 분기)", "资本开支（最近季度）", "設備投資（直近四半期）"],
  "Capex (annual / funding)": ["설비투자 (연간 / 자금조달)", "资本开支（年度 / 融资）", "設備投資（年間 / 資金調達）"],
  "Backlog / contracted": ["수주잔고 / 계약", "积压订单 / 已签约", "受注残 / 契約済み"],
  "Key signal": ["핵심 시그널", "关键信号", "主要シグナル"],
  // ── Coverage (Status tab) ────────────────────────────────────────────────
  "🔴 Enrich now": ["🔴 지금 보강", "🔴 立即补充", "🔴 今すぐ拡充"],
  "🗓 Upcoming": ["🗓 예정", "🗓 即将发布", "🗓 予定"],
  "✅ Covered": ["✅ 반영됨", "✅ 已覆盖", "✅ 反映済み"],
  "Earnings call": ["실적 발표", "业绩电话会", "決算説明会"],
  "Last data": ["최근 데이터", "最新数据", "最新データ"],
  "Enrich": ["보강", "补充", "拡充"],
  "Which enrich to run next, and why: what is fetched and waiting, which companies are overdue for a call or were never enriched, per home market. The 📋 buttons copy the command for Claude Code. Built by enrich_status.py on every graph build and at the end of every enrich run (the same page as ENRICH_STATUS.md in the repo).": ["다음에 실행할 enrich와 그 이유: 시장별로 수집되어 대기 중인 것, 실적 발표 후 기한이 지났거나 한 번도 보강되지 않은 기업. 📋 버튼은 Claude Code용 명령을 복사합니다. 매 그래프 빌드와 매 enrich 실행 종료 시 enrich_status.py가 생성합니다(저장소의 ENRICH_STATUS.md와 같은 내용).", "下一步该运行哪个 enrich 以及原因：按所属市场列出已抓取待处理的内容、电话会后已逾期或从未补充的公司。📋 按钮会复制 Claude Code 的命令。由 enrich_status.py 在每次图谱构建和每次 enrich 运行结束时生成（与仓库中的 ENRICH_STATUS.md 相同）。", "次に実行する enrich とその理由：市場ごとに、取得済みで待機中のもの、説明会後に期限超過の企業、一度も拡充されていない企業。📋 ボタンは Claude Code 用のコマンドをコピーします。グラフのビルドごと、enrich 実行の終了ごとに enrich_status.py が生成（リポジトリの ENRICH_STATUS.md と同じ内容）。"],
  "Pipelines": ["파이프라인", "数据管道", "パイプライン"],
  "One card per enrich pipeline: when it last synced, what reporting period its sources cover, and what is still missing. Generated by enrich_status.py on {date} · {n} source labels in the graph.": ["enrich 파이프라인별 카드: 마지막 동기화 시점, 출처가 다루는 보고 기간, 아직 빠진 것. {date}에 enrich_status.py가 생성 · 그래프 내 출처 라벨 {n}개.", "每个 enrich 管道一张卡片：上次同步时间、来源覆盖的报告期，以及仍缺少的内容。由 enrich_status.py 于 {date} 生成 · 图谱中共 {n} 个来源标签。", "enrich パイプラインごとのカード：最終同期、出典がカバーする報告期間、まだ不足しているもの。{date} に enrich_status.py が生成 · グラフ内の出典ラベル {n}件。"],
  "Last sync": ["마지막 동기화", "上次同步", "最終同期"],
  "Last enriched": ["마지막 보강", "上次补充", "最終拡充"],
  "never": ["없음", "从未", "なし"],
  "Sources cover": ["출처 기간", "来源覆盖", "出典の期間"],
  "Files": ["파일", "文件", "ファイル"],
  "{files} saved · {labels} labels in graph ({entries} entries)": ["{files}개 저장 · 그래프 내 라벨 {labels}개 (항목 {entries}개)", "已保存 {files} 个 · 图谱中 {labels} 个标签（{entries} 条记录）", "{files}件保存 · グラフ内ラベル {labels}件（{entries}項目）"],
  "{n} read": ["{n}개 읽음", "已读 {n} 个", "{n}件読了"],
  "Pending": ["대기", "待处理", "保留中"],
  "{n} not yet enriched": ["{n}개 미보강", "{n} 个尚未补充", "{n}件未拡充"],
  "queue empty": ["대기열 비어 있음", "队列为空", "キューは空"],
  "No data": ["데이터 없음", "无数据", "データなし"],
  "{n} saved, nothing landed": ["{n}개 저장, 반영된 데이터 없음", "已保存 {n} 个，未产生数据", "{n}件保存、反映データなし"],
  "Skipped": ["건너뜀", "已跳过", "スキップ"],
  "{n} filings with no supply-chain content": ["공급망 내용이 없는 공시 {n}건", "{n} 份无供应链内容的公告", "サプライチェーンの内容がない開示 {n}件"],
  "Waiting": ["대기 중", "等待中", "待機中"],
  "call not posted yet": ["실적 발표 원문 미게시", "电话会纪要尚未发布", "説明会の原文は未掲載"],
  "No media": ["미디어 없음", "无媒体", "メディアなし"],
  "{n} 法說會 without a replay video": ["다시보기 영상이 없는 法說會 {n}건", "{n} 场法说会没有回放视频", "再生動画のない法說會 {n}件"],
  "Last run": ["마지막 실행", "上次运行", "最終実行"],
  "{at} · {pages} pages back to {oldest} · {saved} saved": ["{at} · {oldest}까지 {pages}페이지 · {saved}개 저장", "{at} · 回溯 {pages} 页至 {oldest} · 已保存 {saved} 个", "{at} · {oldest}まで{pages}ページ · {saved}件保存"],
  "Show the {n} pending": ["대기 중인 {n}개 보기", "显示 {n} 个待处理项", "保留中の{n}件を表示"],
  "Show the {n} with no data": ["데이터 없는 {n}개 보기", "显示 {n} 个无数据项", "データのない{n}件を表示"],
  "Enriched on:": ["보강 일자:", "补充日期：", "拡充日："],
  "Companies — earnings calendar": ["기업 — 실적 발표 일정", "公司 — 业绩日历", "企業 — 決算カレンダー"],
  "Each listed company's next / most recent earnings call (Yahoo Finance) joined with the freshness of its data in the graph. A call that already happened with no newer data = Enrich now — the 📋 button copies the Transcript:<company> command.": ["상장 기업별 다음 / 최근 실적 발표(Yahoo Finance)와 그래프 내 데이터의 최신성을 함께 보여줍니다. 이미 진행된 실적 발표 이후 새 데이터가 없으면 = 지금 보강 — 📋 버튼은 Transcript:<company> 명령을 복사합니다.", "每家上市公司的下一次 / 最近一次业绩电话会（Yahoo Finance），并结合其在图谱中的数据时效。电话会已召开但没有更新的数据 = 立即补充 — 📋 按钮复制 Transcript:<company> 命令。", "上場企業ごとの次回 / 直近の決算説明会（Yahoo Finance）と、グラフ内データの鮮度を合わせて表示。説明会が終わったのに新しいデータがない = 今すぐ拡充 — 📋 ボタンで Transcript:<company> コマンドをコピー。"],
  "{n} private/unlisted companies not shown.": ["비상장 기업 {n}개는 표시하지 않습니다.", "未显示 {n} 家私营/非上市公司。", "非上場企業 {n}社は表示していません。"],
  "Earnings dates unavailable right now (Yahoo auth failed) — showing coverage from graph data only.": ["지금은 실적 발표일을 가져올 수 없습니다 (Yahoo 인증 실패) — 그래프 데이터 기준 현황만 표시합니다.", "目前无法获取业绩日期（Yahoo 认证失败）— 仅显示基于图谱数据的覆盖情况。", "現在、決算日を取得できません（Yahoo の認証に失敗）— グラフのデータに基づく状況のみ表示しています。"],
  "enrich now": ["지금 보강", "立即补充", "今すぐ拡充"],
  "upcoming ≤14d": ["14일 이내 예정", "14 天内即将发布", "14日以内に予定"],
  "stale (180d)": ["오래됨 (180일)", "过时（180 天）", "古い（180日）"],
  "no signals": ["시그널 없음", "无信号", "シグナルなし"],
  "{n} listed companies tracked": ["추적 중인 상장 기업 {n}개", "跟踪 {n} 家上市公司", "追跡中の上場企業 {n}社"],
  "Search company or ticker…": ["기업 또는 티커 검색…", "搜索公司或代码…", "企業またはティッカーを検索…"],
  "Loading earnings dates…": ["실적 발표일 불러오는 중…", "正在加载业绩日期…", "決算日を読み込み中…"],
  "in {n}d": ["{n}일 후", "{n} 天后", "{n}日後"],
  "no data in 180d": ["180일간 데이터 없음", "180 天内无数据", "180日間データなし"],
  "Copy \"Transcript:{id}\"": ["\"Transcript:{id}\" 복사", "复制 \"Transcript:{id}\"", "\"Transcript:{id}\" をコピー"],
  "{n} shown · dates from Yahoo Finance (best-effort; refreshed ~6h) · \"Covered\" = the graph has data on or after the call date.": ["{n}개 표시 · 일자는 Yahoo Finance 기준 (가능한 범위에서, 약 6시간마다 갱신) · \"반영됨\" = 실적 발표일 당일 또는 이후 데이터가 그래프에 있음.", "显示 {n} 家 · 日期来自 Yahoo Finance（尽力获取；约每 6 小时刷新）·“已覆盖”= 图谱中有电话会当日或之后的数据。", "{n}件を表示 · 日付は Yahoo Finance（取得できる範囲、約6時間ごとに更新）·「反映済み」= 説明会の当日以降のデータがグラフにある。"],
  // ── StatusBoard ──────────────────────────────────────────────────────────
  "call": ["실적 발표", "电话会", "説明会"],
  "DART filing": ["DART 공시", "DART 公告", "DART 開示"],
  "conference": ["컨퍼런스", "会议", "カンファレンス"],
  "IR release": ["IR 보도자료", "IR 新闻稿", "IR リリース"],
  "IR deck": ["IR 자료", "IR 演示材料", "IR 資料"],
  "TDnet filing": ["TDnet 공시", "TDnet 公告", "TDnet 開示"],
  "MOPS filing": ["MOPS 공시", "MOPS 公告", "MOPS 開示"],
  "Run next": ["다음 실행", "下一步运行", "次に実行"],
  "Nothing is due. Every market is current and no queue holds work.": ["처리할 항목이 없습니다. 모든 시장이 최신 상태이며 대기열도 비어 있습니다.", "没有待办事项。所有市场均为最新，队列中没有任务。", "対応が必要なものはありません。すべての市場が最新で、キューも空です。"],
  "Copy \"{cmd}\"": ["\"{cmd}\" 복사", "复制 \"{cmd}\"", "\"{cmd}\" をコピー"],
  "Copy": ["복사", "复制", "コピー"],
  "Shared collectors (every market command runs them first when due): IR feeds synced": ["공용 수집기 (기한이 되면 모든 시장 명령이 먼저 실행): IR 피드 동기화", "共享采集器（到期时每个市场命令都会先运行）：IR 订阅同步于", "共通コレクター（期限が来ると各市場コマンドが最初に実行）：IR フィード同期"],
  "{n} feeds": ["피드 {n}개", "{n} 个订阅源", "フィード {n}件"],
  "due": ["실행 필요", "到期", "要実行"],
  "conference listing walked": ["컨퍼런스 목록 조회", "会议列表抓取于", "カンファレンス一覧の巡回"],
  "Opus verification queue: {n} label(s) waiting (runs at 5+). Board generated {date}.": ["Opus 검증 대기열: 라벨 {n}개 대기 중 (5개 이상이면 실행). 보드 생성 {date}.", "Opus 验证队列：{n} 个标签等待中（满 5 个即运行）。看板生成于 {date}。", "Opus 検証キュー：ラベル {n}件待機中（5件以上で実行）。ボード生成 {date}。"],
  "Needs a decision or setup": ["결정 또는 설정이 필요한 항목", "需要决定或设置", "判断または設定が必要"],
  "Question": ["질문", "问题", "質問"],
  "asked {date}": ["{date} 질문", "提问于 {date}", "{date} に質問"],
  "Markets": ["시장", "市场", "市場"],
  "Market": ["시장", "市场", "市場"],
  "Command": ["명령", "命令", "コマンド"],
  "Call current": ["실적 발표 최신", "电话会为最新", "説明会が最新"],
  "Overdue": ["기한 초과", "已逾期", "期限超過"],
  "Never had a call": ["실적 발표 없음", "从未有电话会", "説明会なし"],
  "No own data": ["자체 데이터 없음", "无自有数据", "自社データなし"],
  "IR feeds": ["IR 피드", "IR 订阅源", "IR フィード"],
  "Collector last ran": ["수집기 마지막 실행", "采集器上次运行", "コレクター最終実行"],
  "run": ["실행", "运行", "実行"],
  "Call current = the latest own earnings call is within the company's usual gap + 3 weeks. No own data = not one entry from the company's own documents yet (new nodes land here). Companies marked \"no source exists\" are left out of Overdue / Never until their recheck date.": ["실적 발표 최신 = 가장 최근 자체 실적 발표가 해당 기업의 평소 간격 + 3주 이내. 자체 데이터 없음 = 아직 기업 자체 문서에서 나온 항목이 하나도 없음 (새 노드가 여기에 표시됨). \"출처 없음\"으로 표시된 기업은 재확인일까지 기한 초과 / 없음에서 제외됩니다.", "电话会为最新 = 公司最近一次自有业绩电话会在其通常间隔 + 3 周之内。无自有数据 = 尚无任何来自公司自有文件的记录（新节点会出现在这里）。标记为“无来源”的公司在复查日期之前不计入已逾期 / 从未。", "説明会が最新 = 直近の自社決算説明会が通常の間隔 + 3週間以内。自社データなし = 自社資料からの項目がまだ1件もない（新しいノードはここに入る）。「出典なし」とマークされた企業は、再確認日まで期限超過 / なしから除外。"],
  "Details by market": ["시장별 상세", "按市场详情", "市場別の詳細"],
  "Nothing missing.": ["빠진 항목이 없습니다.", "没有缺失。", "不足はありません。"],
  "Waiting to enrich": ["보강 대기", "等待补充", "拡充待ち"],
  "Overdue for a call": ["실적 발표 기한 초과", "电话会已逾期", "説明会の期限超過"],
  "last {date}": ["최근 {date}", "上次 {date}", "前回 {date}"],
  "No DART filing": ["DART 공시 없음", "无 DART 公告", "DART 開示なし"],
  "Known gaps": ["알려진 공백", "已知缺口", "既知の欠落"],
  "recheck {date}": ["{date} 재확인", "{date} 复查", "{date} に再確認"],
  "Coordinator notes": ["코디네이터 메모", "协调人备注", "コーディネーターのメモ"],
  // ── Exposure (+ lib/exposure.ts) ─────────────────────────────────────────
  "role": ["역할", "角色", "役割"],
  "contracts": ["계약", "合同", "契約"],
  "capped": ["상한 적용", "封顶", "上限適用"],
  "edges": ["연결", "连线", "エッジ"],
  "fresh": ["최신성", "时效", "鮮度"],
  "Accelerator generations": ["가속기 세대", "加速器世代", "アクセラレーター世代"],
  "Components": ["부품", "零部件", "部品"],
  "new in next gen": ["차세대 신규", "下一代新进", "次世代で新規"],
  "not in next gen": ["차세대에 없음", "未进入下一代", "次世代に不在"],
  "gained": ["신규", "新增", "新規"],
  "lost": ["이탈", "流失", "喪失"],
  "Gen": ["세대", "世代", "世代"],
  "Role in chain": ["체인 내 역할", "在产业链中的角色", "チェーン内の役割"],
  "Contracts": ["계약", "合同", "契約"],
  "Partners": ["거래처", "合作方", "取引先"],
  "Latest": ["최근", "最新", "最新"],
  "Latest signal": ["최근 시그널", "最新信号", "最新シグナル"],
  "Copied {what}": ["{what} 복사됨", "已复制 {what}", "{what} をコピーしました"],
  "Clipboard blocked — copy from the box below": ["클립보드가 차단됨 — 아래 상자에서 복사하세요", "剪贴板被阻止 — 请从下方文本框复制", "クリップボードがブロックされました — 下のボックスからコピーしてください"],
  "{n} tickers": ["티커 {n}개", "{n} 个代码", "ティッカー {n}件"],
  "({n} without a ticker skipped)": ["(티커 없는 {n}개 제외)", "（跳过 {n} 个无代码的公司）", "（ティッカーのない{n}件を除外）"],
  "{n} TradingView symbols": ["TradingView 심볼 {n}개", "{n} 个 TradingView 代码", "TradingView シンボル {n}件"],
  "({n} unmapped skipped)": ["(매핑 안 된 {n}개 제외)", "（跳过 {n} 个无法映射的）", "（未対応の{n}件を除外）"],
  "Exposure — who benefits": ["익스포저 — 누가 수혜를 받나", "敞口 — 谁受益", "エクスポージャー — 誰が恩恵を受けるか"],
  "Pick a chain or a generation transition: its members ranked by how exposed they are — what they make in that chain, how many deals and edges tie them in, and how fresh the evidence is. Click a company for its panel; tick rows to build a basket you can copy into a watchlist.": ["체인이나 세대 전환을 선택하세요: 구성 기업을 익스포저 순으로 보여줍니다 — 그 체인에서 무엇을 만드는지, 거래와 연결이 몇 개인지, 근거가 얼마나 최신인지. 기업을 클릭하면 패널이 열리고, 행을 체크하면 관심 종목에 복사할 바스켓을 만들 수 있습니다.", "选择一个产业链或代际转换：按敞口程度对其成员排名 — 它们在该产业链中生产什么、有多少交易和连线、证据有多新。点击公司打开面板；勾选行可组成一个组合并复制到自选股。", "チェーンまたは世代移行を選択：構成企業をエクスポージャーの大きさで順位付けします — そのチェーンで何を作っているか、取引とエッジの数、根拠の新しさ。企業をクリックでパネル、行にチェックを入れるとウォッチリストにコピーできるバスケットを作れます。"],
  "Chain / transition": ["체인 / 세대 전환", "产业链 / 代际转换", "チェーン / 世代移行"],
  "Filter": ["필터", "筛选", "絞り込み"],
  "Company, ticker, product, sector…": ["기업, 티커, 제품, 섹터…", "公司、代码、产品、板块…", "企業、ティッカー、製品、セクター…"],
  "{n} edges": ["연결 {n}개", "{n} 条连线", "エッジ {n}本"],
  "about": ["중심 기업", "核心公司", "中心企業"],
  "{n} new": ["신규 {n}", "新增 {n}", "新規 {n}"],
  "{n} retained": ["유지 {n}", "保留 {n}", "維持 {n}"],
  "{n} not in next gen": ["차세대에 없음 {n}", "未进入下一代 {n}", "次世代に不在 {n}"],
  "data {date}": ["데이터 {date}", "数据 {date}", "データ {date}"],
  "How is the score computed?": ["점수는 어떻게 계산되나요?", "得分如何计算？", "スコアの算出方法は？"],
  "Loading exposure…": ["익스포저 불러오는 중…", "正在加载敞口…", "エクスポージャーを読み込み中…"],
  "Exposure data has not been generated yet (/data/exposure.json is missing). Run python graph_build.py --sync in the repo root — derive.py writes graph/exposure.json and the sync copies it here. The generation delta below still works because it is computed from the graph itself.": ["익스포저 데이터가 아직 생성되지 않았습니다 (/data/exposure.json 없음). 저장소 루트에서 python graph_build.py --sync를 실행하세요 — derive.py가 graph/exposure.json을 쓰고 동기화가 이곳으로 복사합니다. 아래의 세대 변화는 그래프에서 직접 계산하므로 계속 작동합니다.", "敞口数据尚未生成（缺少 /data/exposure.json）。请在仓库根目录运行 python graph_build.py --sync — derive.py 会写入 graph/exposure.json，同步会将其复制到这里。下方的代际变化仍可使用，因为它直接由图谱计算。", "エクスポージャーのデータはまだ生成されていません（/data/exposure.json がありません）。リポジトリのルートで python graph_build.py --sync を実行してください — derive.py が graph/exposure.json を書き出し、同期でここにコピーされます。下の世代間の差分はグラフから直接算出するため引き続き使えます。"],
  "Filter by layer": ["레이어로 필터", "按层级筛选", "レイヤーで絞り込み"],
  "in basket": ["바스켓에 담김", "在组合中", "バスケット内"],
  "Copy tickers": ["티커 복사", "复制代码", "ティッカーをコピー"],
  "Copy TradingView list": ["TradingView 목록 복사", "复制 TradingView 列表", "TradingView リストをコピー"],
  "Visible rows — only the ticked ones when the basket holds any of them": ["표시된 행 — 바스켓에 담긴 행이 있으면 체크한 행만", "可见行 — 如果组合中有可见行，则只导出勾选的行", "表示中の行 — バスケットに入っている行があればチェックした行のみ"],
  "Download CSV ({n} selected)": ["CSV 다운로드 (선택 {n})", "下载 CSV（已选 {n}）", "CSVをダウンロード（選択 {n}）"],
  "Download CSV ({n} visible)": ["CSV 다운로드 (표시 {n})", "下载 CSV（可见 {n}）", "CSVをダウンロード（表示 {n}）"],
  "Clear basket": ["바스켓 비우기", "清空组合", "バスケットを空にする"],
  "Text to copy": ["복사할 텍스트", "要复制的文本", "コピーするテキスト"],
  "Select all visible rows": ["표시된 행 모두 선택", "全选可见行", "表示中の行をすべて選択"],
  "Add {name} to basket": ["{name} 바스켓에 담기", "将 {name} 加入组合", "{name} をバスケットに追加"],
  "Not in the next-generation chain": ["차세대 체인에 없음", "不在下一代产业链中", "次世代チェーンに不在"],
  "{n} edges in {chain}": ["{chain}의 연결 {n}개", "{chain} 中 {n} 条连线", "{chain} のエッジ {n}本"],
  "Distinct counterparties in this chain": ["이 체인 내 서로 다른 거래 상대방 수", "该产业链中不同交易对手的数量", "このチェーン内の異なる取引相手の数"],
  "No dated source yet": ["날짜가 있는 출처 없음", "暂无带日期的来源", "日付付きの出典はまだありません"],
  "{n} days ago": ["{n}일 전", "{n} 天前", "{n}日前"],
  "No TradingView mapping for this exchange": ["이 거래소는 TradingView 매핑이 없습니다", "该交易所没有 TradingView 映射", "この取引所は TradingView に対応していません"],
  "No companies match.": ["일치하는 기업이 없습니다.", "没有匹配的公司。", "一致する企業はありません。"],
  "{n} of {total} companies · score max {max} — hover a score for its breakdown": ["기업 {total}개 중 {n}개 · 최대 점수 {max} — 점수에 마우스를 올리면 내역 표시", "{total} 家公司中的 {n} 家 · 满分 {max} — 悬停在得分上查看明细", "{total}社中 {n}社 · 最高スコア {max} — スコアにカーソルを合わせると内訳を表示"],
  "{n}d": ["{n}일", "{n} 天", "{n}日"],
  "older": ["그 이전", "更早", "それ以前"],
  "Gen = status in {label}": ["세대 = {label}에서의 상태", "世代 = 在 {label} 中的状态", "世代 = {label} での状態"],
  "Generation delta": ["세대 간 변화", "代际变化", "世代間の差分"],
  "Who wins a socket, who is not in the next-gen chain, and whose content changes. Computed from the curated chains; click a company for details.": ["누가 소켓을 확보하고, 누가 차세대 체인에 없으며, 누구의 탑재 콘텐츠가 바뀌는지. 큐레이션된 체인에서 계산하며, 기업을 클릭하면 상세 정보가 열립니다.", "谁赢得份额（socket）、谁不在下一代产业链中、谁的含量发生变化。基于人工整理的产业链计算；点击公司查看详情。", "誰がソケットを獲得し、誰が次世代チェーンに不在で、誰の搭載内容が変わるか。キュレーションされたチェーンから算出。企業をクリックで詳細を表示。"],
  "won a socket it did not have in the current generation": ["현 세대에는 없던 소켓을 확보", "赢得了本代没有的份额（socket）", "現世代にはなかったソケットを獲得"],
  "Retained, content changed": ["유지, 콘텐츠 변화", "保留，含量变化", "維持、搭載内容が変化"],
  "retained in both generations with a different product — the content delta ({n} retained in total)": ["두 세대 모두 유지되지만 제품이 다름 — 콘텐츠 변화 (전체 유지 {n}개)", "两代均保留但产品不同 — 含量变化（共保留 {n} 家）", "両世代で維持されるが製品が異なる — 搭載内容の差分（維持は合計{n}社）"],
  "Customer / supplier concentration": ["고객 / 공급사 집중도", "客户 / 供应商集中度", "顧客 / サプライヤーの集中度"],
  "Facts the companies filed themselves (major-customer tables, raw-material suppliers, supply contracts as a share of revenue) for the members of this selection. The share is the first percentage in the text — it can be an aggregate, so read the detail.": ["선택한 구성 기업들이 직접 공시한 사실 (주요 고객 표, 원재료 공급사, 매출 대비 공급계약 비중). 비중은 본문의 첫 번째 퍼센트이며 합계일 수 있으니 상세 내용을 확인하세요.", "所选成员公司自行披露的事实（主要客户表、原材料供应商、供货合同占营收比例）。占比为文本中的第一个百分比 — 可能是合计值，请阅读详情。", "選択した構成企業が自ら開示した事実（主要顧客の表、原材料のサプライヤー、売上に占める供給契約の割合）。割合は本文中の最初のパーセントで、合計値の場合もあるので詳細を確認してください。"],
  "No concentration facts filed for these companies yet.": ["이 기업들에 대해 공시된 집중도 정보가 아직 없습니다.", "这些公司尚未披露集中度信息。", "これらの企業について開示された集中度の情報はまだありません。"],
  "Counterparty": ["거래 상대방", "交易对手", "取引相手"],
  "Role": ["역할", "角色", "役割"],
  "Share": ["비중", "占比", "割合"],
  "Detail": ["상세", "详情", "詳細"],
  "customer": ["고객", "客户", "顧客"],
  "supplier": ["공급사", "供应商", "サプライヤー"],
  // ── AskGraph ─────────────────────────────────────────────────────────────
  "Rewriting the question…": ["질문을 다시 쓰는 중…", "正在改写问题…", "質問を書き換え中…"],
  "Reading the graph…": ["그래프를 읽는 중…", "正在读取图谱…", "グラフを読み込み中…"],
  "Thinking…": ["생각하는 중…", "思考中…", "考え中…"],
  "Ask a follow-up…": ["후속 질문하기…", "继续追问…", "追加で質問…"],
  "e.g. Who supplies HBM4 for NVIDIA Vera Rubin?": ["예: NVIDIA Vera Rubin에 HBM4를 공급하는 곳은?", "例如：谁为 NVIDIA Vera Rubin 供应 HBM4？", "例：NVIDIA Vera Rubin に HBM4 を供給しているのは？"],
  "Your follow-up question": ["후속 질문", "你的追问", "追加の質問"],
  "Your question": ["질문", "你的问题", "質問"],
  "Follow up": ["후속 질문", "追问", "追加質問"],
  "Ask the Graph": ["그래프에 질문하기", "向图谱提问", "グラフに質問"],
  "Ask in English or Korean; the answer comes in the language picked at the top of the page. The answer is written only from the signals and contracts stored in this graph (transcript-grounded data) — every claim is cited to its source label, and when the graph does not contain the answer it says so. Follow-up questions see the earlier answers of the conversation.": ["영어나 한국어로 질문하세요. 답변은 페이지 상단에서 고른 언어로 작성됩니다. 답변은 이 그래프에 저장된 시그널과 계약(실적 발표 원문 기반 데이터)만으로 작성되며, 모든 주장에는 출처 라벨이 달리고, 그래프에 답이 없으면 없다고 말합니다. 후속 질문은 대화의 이전 답변을 참고합니다.", "可用英文或韩文提问；回答将使用页面顶部选择的语言。回答仅基于图谱中存储的信号和合同（基于电话会议原文的数据）— 每条论断都标注来源标签，图谱中没有答案时会如实说明。追问会参考本次对话中之前的回答。", "英語または韓国語で質問してください。回答はページ上部で選んだ言語で書かれます。回答はこのグラフに保存されたシグナルと契約（説明会の原文に基づくデータ）のみから作成され、すべての主張に出典ラベルが付き、グラフに答えがない場合はそう伝えます。追加の質問は、会話のこれまでの回答を踏まえます。"],
  "Suggested questions": ["추천 질문", "推荐问题", "おすすめの質問"],
  "Conversation · {n} of up to {max} turns — a follow-up sees the earlier answers. Kept only while this tab is open.": ["대화 · 최대 {max}개 중 {n}개 — 후속 질문은 이전 답변을 참고합니다. 이 탭이 열려 있는 동안만 유지됩니다.", "对话 · 最多 {max} 轮中的第 {n} 轮 — 追问会参考之前的回答。仅在此标签页打开期间保留。", "会話 · 最大{max}ターン中 {n} — 追加の質問はこれまでの回答を踏まえます。このタブを開いている間だけ保持されます。"],
  "New conversation": ["새 대화", "新对话", "新しい会話"],
  "chains:": ["체인:", "产业链：", "チェーン："],
  "topics:": ["주제:", "主题：", "トピック："],
  "{n} snippet matched": ["일치한 스니펫 {n}개", "匹配到 {n} 条片段", "一致したスニペット {n}件"],
  "{n} snippets matched": ["일치한 스니펫 {n}개", "匹配到 {n} 条片段", "一致したスニペット {n}件"],
  "intent:": ["의도:", "意图：", "意図："],
  "searched:": ["검색어:", "搜索：", "検索語："],
  "lookup": ["조회", "查询", "照会"],
  "compare": ["비교", "比较", "比較"],
  "rank": ["순위", "排名", "ランキング"],
  "timeline": ["타임라인", "时间线", "タイムライン"],
  "The local engine (Opus, max effort) takes 15–60 s for most questions and up to a few minutes for a ranking in Korean.": ["로컬 엔진(Opus, 최대 추론)은 대부분의 질문에 15–60초, 한국어 순위 질문에는 몇 분까지 걸립니다.", "本地引擎（Opus，最大推理强度）处理大多数问题需要 15–60 秒，韩文排名类问题最多需要几分钟。", "ローカルエンジン（Opus、最大推論）はほとんどの質問に15–60秒、韓国語のランキング質問には数分かかることがあります。"],
  "{in} in / {out} out tokens": ["입력 {in} / 출력 {out} 토큰", "输入 {in} / 输出 {out} 令牌", "入力 {in} / 出力 {out} トークン"],
  "answer cut at the token limit": ["토큰 한도에서 답변이 잘림", "回答在令牌上限处被截断", "トークン上限で回答が途切れました"],
  "the model declined to answer this": ["모델이 이 질문에 답변을 거부함", "模型拒绝回答此问题", "モデルがこの質問への回答を拒否しました"],
  "Context used — {n} snippets sent to the model": ["사용된 컨텍스트 — 모델에 보낸 스니펫 {n}개", "使用的上下文 — 发送给模型的 {n} 条片段", "使用したコンテキスト — モデルに送ったスニペット {n}件"],
  "signal": ["시그널", "信号", "シグナル"],
  "contract": ["계약", "合同", "契約"],
  "Show snippet {n}": ["스니펫 {n} 보기", "显示片段 {n}", "スニペット {n} を表示"],
  "effort {e}": ["추론 {e}", "推理强度 {e}", "推論 {e}"],
  "your machine": ["내 컴퓨터", "你的电脑", "自分のPC"],
  "The graph has a node for {names} but no stored signals or contracts matched this question, so there is nothing to answer from yet. Enrich its latest earnings call or filing to fill this in.": ["그래프에 {names} 노드는 있지만 이 질문과 일치하는 저장된 시그널이나 계약이 없어 아직 답변할 근거가 없습니다. 최신 실적 발표나 공시를 보강해 채워 주세요.", "图谱中有 {names} 的节点，但没有与此问题匹配的已存信号或合同，因此暂时无从回答。请补充其最新的业绩电话会或公告。", "グラフには {names} のノードがありますが、この質問に一致する保存済みのシグナルや契約がないため、まだ回答できません。最新の決算説明会や開示を拡充してください。"],
  "No stored signal or contract matched this question, so there is nothing to answer from. Try naming a company (SK Hynix, TSMC, Vertiv…) or a product generation (Vera Rubin, B200, MI450 Helios, TPU v8, Trainium3), or a topic like HBM, CoWoS, CPO or transformers.": ["이 질문과 일치하는 저장된 시그널이나 계약이 없어 답변할 근거가 없습니다. 기업(SK Hynix, TSMC, Vertiv…)이나 제품 세대(Vera Rubin, B200, MI450 Helios, TPU v8, Trainium3), 또는 HBM, CoWoS, CPO, 변압기 같은 주제를 넣어 보세요.", "没有与此问题匹配的已存信号或合同，因此无从回答。请尝试指定公司（SK Hynix、TSMC、Vertiv…）、产品世代（Vera Rubin、B200、MI450 Helios、TPU v8、Trainium3），或 HBM、CoWoS、CPO、变压器等主题。", "この質問に一致する保存済みのシグナルや契約がないため、回答できません。企業名（SK Hynix、TSMC、Vertiv…）、製品世代（Vera Rubin、B200、MI450 Helios、TPU v8、Trainium3）、または HBM、CoWoS、CPO、変圧器などのトピックを入れてみてください。"],
  "Ask the Graph has no answer engine configured yet.": ["그래프 질문 기능에 아직 답변 엔진이 설정되지 않았습니다.", "“向图谱提问”尚未配置回答引擎。", "「グラフに質問」の回答エンジンがまだ設定されていません。"],
  "Who supplies HBM4 for NVIDIA Vera Rubin?": ["NVIDIA Vera Rubin에 HBM4를 공급하는 곳은?", "谁为 NVIDIA Vera Rubin 供应 HBM4？", "NVIDIA Vera Rubin に HBM4 を供給しているのは？"],
  "Which companies report supply as sold out or on allocation?": ["공급이 완판되었거나 할당 중이라고 밝힌 기업은?", "哪些公司表示供应已售罄或处于配额分配？", "供給が完売または割当制だと報告している企業は？"],
  "How much capex are the hyperscalers guiding for this year?": ["하이퍼스케일러들의 올해 설비투자 가이던스는?", "超大规模云厂商今年的资本开支指引是多少？", "ハイパースケーラーの今年の設備投資ガイダンスは？"],
  "When does co-packaged optics (CPO) reach volume, according to the graph?": ["그래프에 따르면 CPO(공동 패키징 광학)는 언제 양산 규모에 도달하나?", "根据图谱，共封装光学（CPO）何时实现量产？", "グラフによると、CPO（コパッケージド・オプティクス）はいつ量産規模に達する？"],
  "Who is winning 1.6T optical transceiver and DSP business?": ["1.6T 광 트랜시버와 DSP 사업을 수주하는 곳은?", "谁在赢得 1.6T 光模块和 DSP 业务？", "1.6T 光トランシーバーと DSP の事業を獲得しているのは？"],
  "Which power and cooling suppliers report record backlog from data centers?": ["데이터센터발 사상 최대 수주잔고를 보고한 전력·냉각 공급사는?", "哪些电力与散热供应商报告了来自数据中心的创纪录积压订单？", "データセンター向けで過去最高の受注残を報告している電力・冷却サプライヤーは？"],
  "What do suppliers say about AWS Trainium3?": ["공급사들은 AWS Trainium3에 대해 뭐라고 하나?", "供应商如何评价 AWS Trainium3？", "サプライヤーは AWS Trainium3 について何と言っている？"],
  "What is the latest on AMD MI450 Helios?": ["AMD MI450 Helios의 최신 소식은?", "AMD MI450 Helios 的最新动态是什么？", "AMD MI450 Helios の最新情報は？"],
  "What does the graph say about Google TPU demand and its suppliers?": ["그래프에서 Google TPU 수요와 공급사에 대해 알 수 있는 것은?", "图谱对谷歌 TPU 需求及其供应商有何记录？", "Google TPU の需要とそのサプライヤーについて、グラフには何がある？"],
  // ── LiveQuote / Fundamentals ─────────────────────────────────────────────
  "Loading live quote…": ["실시간 시세 불러오는 중…", "正在加载实时报价…", "リアルタイム株価を読み込み中…"],
  "Live quote unavailable.": ["실시간 시세를 사용할 수 없습니다.", "实时报价不可用。", "リアルタイム株価は利用できません。"],
  "Mkt cap": ["시가총액", "市值", "時価総額"],
  "52-wk": ["52주", "52 周", "52週"],
  "1D": ["1일", "1天", "1日"],
  "1W": ["1주", "1周", "1週"],
  "1M": ["1개월", "1个月", "1カ月"],
  "YTD": ["연초 대비", "年初至今", "年初来"],
  "1Y": ["1년", "1年", "1年"],
  "5Y": ["5년", "5年", "5年"],
  "Trailing 12-month P/E": ["최근 12개월 P/E", "过去 12 个月市盈率（P/E）", "過去12カ月のP/E"],
  "Forward P/E (next fiscal year consensus EPS)": ["선행 P/E (다음 회계연도 컨센서스 EPS)", "预期市盈率（下一财年一致预期 EPS）", "予想P/E（来期コンセンサスEPS）"],
  "PEG ratio": ["PEG 비율", "PEG 比率", "PEGレシオ"],
  "Price / book": ["주가 / 장부가 (P/B)", "市净率（P/B）", "株価純資産倍率（P/B）"],
  "Price / sales (TTM)": ["주가 / 매출 (최근 12개월)", "市销率（TTM）", "株価売上高倍率（TTM）"],
  "Enterprise value / EBITDA": ["기업가치 / EBITDA", "企业价值 / EBITDA", "企業価値 / EBITDA"],
  "Return on equity": ["자기자본이익률 (ROE)", "净资产收益率（ROE）", "自己資本利益率（ROE）"],
  "Revenue growth, latest quarter YoY": ["최근 분기 매출 성장률 (전년 대비)", "最近季度营收同比增长", "直近四半期の売上高成長率（前年比）"],
  "Gross margin (TTM)": ["매출총이익률 (최근 12개월)", "毛利率（TTM）", "粗利益率（TTM）"],
  "Operating margin (TTM)": ["영업이익률 (최근 12개월)", "营业利润率（TTM）", "営業利益率（TTM）"],
  "Dividend yield": ["배당수익률", "股息率", "配当利回り"],
  "Analyst mean price target (number of analysts)": ["애널리스트 평균 목표주가 (애널리스트 수)", "分析师平均目标价（分析师人数）", "アナリスト平均目標株価（アナリスト数）"],
  "Target": ["목표가", "目标价", "目標株価"],
  "Div": ["배당", "股息", "配当"],
  // @@END
};
